import { LanguageConfig, SupportedLanguageCode } from '../types';

export const SUPPORTED_LANGUAGES: LanguageConfig[] = [
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    script: 'Devanagari',
    speechLocale: 'hi-IN',
    greetingText: 'नमस्ते! मैं आपकी भारत ट्यूलिप सहायक हूँ।',
    welcomePrompt: 'कृपया अपनी भाषा चुनें। मैं आपकी अपनी भाषा में सहायता करूंगी।',
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'Tamil',
    speechLocale: 'ta-IN',
    greetingText: 'வணக்கம்! நான் உங்கள் பாரத் துலிப் குரல் உதவியாளர்.',
    welcomePrompt: 'தயவுசெய்து உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்.',
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    script: 'Telugu',
    speechLocale: 'te-IN',
    greetingText: 'నమస్కారం! నేను మీ భారత్ ట్యులిప్ వాయిస్ అసిస్టెంట్‌ని.',
    welcomePrompt: 'దయచేసి మీ ప్రాంతీయ భాషను ఎంచుకోండి.',
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    script: 'Bengali',
    speechLocale: 'bn-IN',
    greetingText: 'নমস্কার! আমি আপনার ভারত টিউলিপ ভয়েস সহকারী।',
    welcomePrompt: 'অনুগ্রহ করে আপনার ভাষা নির্বাচন করুন।',
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    script: 'Devanagari',
    speechLocale: 'mr-IN',
    greetingText: 'नमस्कार! मी तुमची भारत ट्यूलिप व्हॉईस सहाय्यक आहे.',
    welcomePrompt: 'कृपया तुमची भाषा निवडा.',
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    script: 'Gujarati',
    speechLocale: 'gu-IN',
    greetingText: 'નમસ્તે! હું તમારી ભારત ટ્યૂલિપ વૉઇસ સહાયક છું.',
    welcomePrompt: 'કૃપા કરીને તમારી ભાષા પસંદ કરો.',
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    script: 'Kannada',
    speechLocale: 'kn-IN',
    greetingText: 'ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ ಭಾರತ ಟುಲಿಪ್ ವಾಯ್ಸ್ ಸಹಾಯಕ.',
    welcomePrompt: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    script: 'Malayalam',
    speechLocale: 'ml-IN',
    greetingText: 'നമസ്കാരം! ഞാൻ നിങ്ങളുടെ ഭാരത് ട്യൂലിപ് വോയ്സ് സഹായി.',
    welcomePrompt: 'ദയവായി നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക.',
  },
  {
    code: 'or',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    script: 'Odia',
    speechLocale: 'or-IN',
    greetingText: 'ନମସ୍କାର! ମୁଁ ଆପଣଙ୍କ ଭାରତ ଟିଉଲିପ୍ ଭଏସ୍ ସହାୟକ।',
    welcomePrompt: 'ଦୟାକରି ଆପଣଙ୍କ ଭାଷା ଚୟନ କରନ୍ତୁ।',
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    script: 'Gurmukhi',
    speechLocale: 'pa-IN',
    greetingText: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਤੁਹਾਡੀ ਭਾਰਤ ਟਿਊਲਿਪ ਵਾਇਸ ਸਹਾਇਕ ਹਾਂ।',
    welcomePrompt: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਬੋਲੀ ਚੁਣੋ।',
  },
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    script: 'Latin',
    speechLocale: 'en-IN',
    greetingText: 'Welcome! I am your Bharat TULIP Voice Assistant.',
    welcomePrompt: 'Please select your preferred language.',
  },
];

export interface UiTranslations {
  appTitle: string;
  appSubtitle: string;
  voiceAssistant: string;
  askLanguage: string;
  tapToSpeak: string;
  listening: string;
  aiThinking: string;
  speaking: string;
  // Step 1: Onboarding
  onboardingTitle: string;
  askNamePrompt: string;
  askVillagePrompt: string;
  askCraftPrompt: string;
  nameLabel: string;
  villageLabel: string;
  craftLabel: string;
  createAccountBtn: string;
  accountCreated: string;
  // Step 2: Product Selling Steps
  sellPageTitle: string;
  stepPhotoTitle: string;
  stepPhotoPrompt: string;
  stepPhotoAiEnhance: string;
  takePhotoBtn: string;
  uploadPhotoBtn: string;
  originalPhoto: string;
  studioPhoto: string;
  stepDescTitle: string;
  stepDescPrompt: string;
  stepDescExample: string;
  stepDescAiEnhance: string;
  stepPriceTitle: string;
  stepPricePrompt: string;
  stepPriceMarketCompare: string;
  suggestedPriceLabel: string;
  yourPriceLabel: string;
  fairPriceBadge: string;
  // Step 3: Review & Publish
  reviewTitle: string;
  reviewPrompt: string;
  publishBtn: string;
  publishing: string;
  productPublishedSuccess: string;
  viewInStorefront: string;
  // Dashboard & Metrics
  dashboardTitle: string;
  totalSales: string;
  activeOrders: string;
  revenueTrends: string;
  inventoryControl: string;
  orderManagement: string;
  filterAll: string;
  filterPending: string;
  filterFulfilled: string;
  filterCanceled: string;
  stockInStock: string;
  stockLow: string;
  stockOut: string;
  quickPriceEdit: string;
  saveChanges: string;
  // Buyer View
  buyerStoreTitle: string;
  buyFromArtisan: string;
  verifiedArtisan: string;
  fairPriceGuarantee: string;
  addToCart: string;
  orderPlaced: string;
  // Database Inspector
  dbInspectorTitle: string;
  supabaseSynced: string;
  localStorageFallback: string;
  tableArtisans: string;
  tableProducts: string;
  tableOrders: string;
  schemaDetails: string;
}

export const TRANSLATIONS: Record<SupportedLanguageCode, UiTranslations> = {
  hi: {
    appTitle: 'भारत ट्यूलिप कारीगर साथी',
    appSubtitle: 'आवाज़ से बनाएं अपना ऑनलाइन स्टोर और बढ़ाएं आमदनी',
    voiceAssistant: 'आवाज़ सहायक',
    askLanguage: 'कृपया अपनी क्षेत्रीय भाषा चुनें',
    tapToSpeak: 'बोलने के लिए माइक दबाएं',
    listening: 'मैं आपकी बात सुन रही हूँ...',
    aiThinking: 'एआई सोच रहा है...',
    speaking: 'बोल रही हूँ...',
    onboardingTitle: 'कारीगर पंजीकरण (केवल बोलकर)',
    askNamePrompt: 'नमस्ते कारीगर जी! कृपया अपना शुभ नाम बताइए।',
    askVillagePrompt: 'बहुत अच्छा! आप किस गांव या शहर से हैं?',
    askCraftPrompt: 'आप किस पारंपरिक हस्तकला या उत्पाद को बनाते हैं?',
    nameLabel: 'कारीगर का नाम',
    villageLabel: 'गांव / शहर',
    craftLabel: 'हस्तकला विधा',
    createAccountBtn: 'खाता बनाएं और दुकान शुरू करें',
    accountCreated: 'आपका कारीगर खाता सफलतापूर्वक बन गया है!',
    sellPageTitle: 'नया उत्पाद जोड़ें (3 आसान कदम)',
    stepPhotoTitle: 'कदम 1: उत्पाद की फोटो लें',
    stepPhotoPrompt: 'कारीगर जी, अपने उत्पाद की एक साफ फोटो कैमरे से खींचिए।',
    stepPhotoAiEnhance: 'एआई खराब बैकग्राउंड हटाकर इसे स्टूडियो फोटो बना देगा।',
    takePhotoBtn: 'कैमरा खोलें',
    uploadPhotoBtn: 'फोटो अपलोड करें',
    originalPhoto: 'आपकी खींची हुई फोटो',
    studioPhoto: 'एआई स्टूडियो फोटो (सफेद व साफ बैकग्राउंड)',
    stepDescTitle: 'कदम 2: उत्पाद के बारे में बोलकर बताएं',
    stepDescPrompt: 'यह उत्पाद आपने कैसे बनाया, कौनसी सामग्री प्रयोग की? अपनी भाषा में बोलें।',
    stepDescExample: '"यह मिट्टी का फूलदान मैंने प्राकृतिक चिकनी मिट्टी से चाक पर बनाया है..."',
    stepDescAiEnhance: 'एआई आपके शब्दों को ऑनलाइन खरीदारों के लिए आकर्षक विवरण में बदल देगा।',
    stepPriceTitle: 'कदम 3: आप इसकी क्या कीमत चाहते हैं?',
    stepPricePrompt: 'कारीगर जी, बोलकर बताइए आप इसे कितने रुपये में बेचना चाहते हैं?',
    stepPriceMarketCompare: 'एआई बाजार में समान उत्पादों के भाव देखकर सही कीमत बताएगा।',
    suggestedPriceLabel: 'एआई अनुशंसित बाजार मूल्य',
    yourPriceLabel: 'आपकी तय कीमत',
    fairPriceBadge: 'उचित कारीगर लाभ गारंटी (80%+)',
    reviewTitle: 'कदम 4: अंतिम समीक्षा और प्रकाशन',
    reviewPrompt: 'सब तैयार है! क्या आप इसे भारत ट्यूलिप पर प्रकाशित करना चाहते हैं?',
    publishBtn: 'दुकान में प्रकाशित करें (Live Sell)',
    publishing: 'उत्पाद प्रकाशित हो रहा है...',
    productPublishedSuccess: 'बधाई हो! आपका उत्पाद लाइव हो चुका है।',
    viewInStorefront: 'खरीदार की दुकान में देखें',
    dashboardTitle: 'कारीगर डैशबोर्ड',
    totalSales: 'कुल बिक्री आय',
    activeOrders: 'सक्रिय आर्डर',
    revenueTrends: 'मासिक बिक्री ग्राफ',
    inventoryControl: 'स्टॉक व उत्पाद सूची',
    orderManagement: 'ग्राहक आर्डर प्रबंधन',
    filterAll: 'सभी',
    filterPending: 'लंबित',
    filterFulfilled: 'पूर्ण',
    filterCanceled: 'रद्द',
    stockInStock: 'उपलब्ध',
    stockLow: 'कम स्टॉक',
    stockOut: 'समाप्त',
    quickPriceEdit: 'कीमत बदलें',
    saveChanges: 'सहेजें',
    buyerStoreTitle: 'भारत ट्यूलिप कारीगर बाजार',
    buyFromArtisan: 'सीधे कारीगर से खरीदें',
    verifiedArtisan: 'सत्यापित ग्रामीण कारीगर',
    fairPriceGuarantee: '100% प्रामाणिक हस्तशिल्प',
    addToCart: 'अभी खरीदें (Cash on Delivery / UPI)',
    orderPlaced: 'आर्डर सफलतापूर्वक दर्ज हो गया!',
    dbInspectorTitle: 'सुपाबेस एंड-टू-एंड डेटाबेस दृश्य',
    supabaseSynced: 'सुपाबेस से सिंक है',
    localStorageFallback: 'स्थानीय डेटाबेस एक्टिव',
    tableArtisans: 'कारीगर तालिका (artisans)',
    tableProducts: 'उत्पाद तालिका (products)',
    tableOrders: 'आर्डर तालिका (orders)',
    schemaDetails: 'डेटाबेस स्कीमा और रिकॉर्ड्स',
  },
  ta: {
    appTitle: 'பாரத் துலிப் கைவினைஞர் மையம்',
    appSubtitle: 'குரல் வழியே உங்கள் தயாரிப்புகளை நேரடியாக விற்கலாம்',
    voiceAssistant: 'குரல் உதவியாளர்',
    askLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    tapToSpeak: 'பேச மைக்-ஐ அழுத்தவும்',
    listening: 'நான் கேட்டுக்கொண்டிருக்கிறேன்...',
    aiThinking: 'சிந்திக்கிறது...',
    speaking: 'பேசுகிறது...',
    onboardingTitle: 'கைவினைஞர் குரல் பதிவு',
    askNamePrompt: 'வணக்கம்! உங்கள் பெயர் என்ன என்று சொல்லுங்கள்.',
    askVillagePrompt: 'நீங்கள் எந்த ஊர் அல்லது கிராமத்திலிருந்து வருகிறீர்கள்?',
    askCraftPrompt: 'நீங்கள் என்ன விதமான கைவினைப் பொருளை செய்கிறீர்கள்?',
    nameLabel: 'கைவினைஞர் பெயர்',
    villageLabel: 'ஊர் / கிராமம்',
    craftLabel: 'கைவினை வகை',
    createAccountBtn: 'கணக்கை உருவாக்கி தொடங்கவும்',
    accountCreated: 'உங்கள் கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது!',
    sellPageTitle: 'புதிய தயாரிப்பைச் சேர்க்கவும் (3 எளிய படிகள்)',
    stepPhotoTitle: 'படி 1: தயாரிப்பின் புகைப்படம் எடுக்கவும்',
    stepPhotoPrompt: 'உங்கள் கைவினைப் பொருளின் புகைப்படத்தை கேமராவில் எடுக்கவும்.',
    stepPhotoAiEnhance: 'AI பின்னணியை நீக்கி ஸ்டுடியோ புகைப்படமாக மாற்றும்.',
    takePhotoBtn: 'கேமராவைத் திறக்கவும்',
    uploadPhotoBtn: 'படம் பதிவேற்றவும்',
    originalPhoto: 'நீங்கள் எடுத்த புகைப்படம்',
    studioPhoto: 'AI ஸ்டுடியோ புகைப்படம்',
    stepDescTitle: 'படி 2: தயாரிப்பு பற்றி குரலில் விவரிக்கவும்',
    stepDescPrompt: 'இதை நீங்கள் எப்படி செய்தீர்கள் என்று உங்கள் சொந்த மொழியில் சொல்லுங்கள்.',
    stepDescExample: '"இந்த பட்டு சால்வை பாரம்பரிய தறியில் நெய்யப்பட்டது..."',
    stepDescAiEnhance: 'AI இதை கவர்ச்சிகரமான விற்பனை விவரமாக மாற்றும்.',
    stepPriceTitle: 'படி 3: நீங்கள் விரும்பும் விலை என்ன?',
    stepPricePrompt: 'இதற்கு நீங்கள் எவ்வளவு விலை கேட்கிறீர்கள் என்று சொல்லுங்கள்.',
    stepPriceMarketCompare: 'AI சந்தை விலையுடன் ஒப்பிட்டு நியாயமான விலையை பரிந்துரைக்கும்.',
    suggestedPriceLabel: 'AI பரிந்துரைத்த சந்தை விலை',
    yourPriceLabel: 'உங்கள் விலை',
    fairPriceBadge: 'நியாயமான கைவினைஞர் வருவாய்',
    reviewTitle: 'படி 4: இறுதி சரிபார்ப்பு & வெளியீடு',
    reviewPrompt: 'எல்லாம் தயாராக உள்ளது! சந்தையில் வெளியிடலாமா?',
    publishBtn: 'விற்பனைக்கு வெளியிடவும்',
    publishing: 'வெளியிடப்படுகிறது...',
    productPublishedSuccess: 'வாழ்த்துகள்! உங்கள் பொருள் விற்பனைக்கு வந்துவிட்டது.',
    viewInStorefront: 'வாங்குபவர் பக்கத்தில் பார்க்கவும்',
    dashboardTitle: 'கைவினைஞர் கட்டுப்பாட்டு பலகை',
    totalSales: 'மொத்த விற்பனை',
    activeOrders: 'செயலில் உள்ள ஆர்டர்கள்',
    revenueTrends: 'வருவாய் போக்கு',
    inventoryControl: 'சரக்கு இருப்பு & விலை',
    orderManagement: 'ஆர்டர் மேலாண்மை',
    filterAll: 'அனைத்தும்',
    filterPending: 'நிலுவை',
    filterFulfilled: 'நிறைவேற்றப்பட்டது',
    filterCanceled: 'ரத்துசெய்யப்பட்டது',
    stockInStock: 'இருப்பு உள்ளது',
    stockLow: 'குறைந்த இருப்பு',
    stockOut: 'தீர்ந்துவிட்டது',
    quickPriceEdit: 'விலை திருத்தம்',
    saveChanges: 'சேமி',
    buyerStoreTitle: 'பாரத் துலிப் சந்தை',
    buyFromArtisan: 'நேரடியாக கைவினைஞரிடம் வாங்கவும்',
    verifiedArtisan: 'சரிபார்க்கப்பட்ட கிராமிய கைவினைஞர்',
    fairPriceGuarantee: '100% அசல் கைவினைப்பொருள்',
    addToCart: 'இப்போதே வாங்கவும்',
    orderPlaced: 'ஆர்டர் வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
    dbInspectorTitle: 'சுபாபேஸ் தரவுத்தள பார்வை',
    supabaseSynced: 'சுபாபேஸுடன் இணைக்கப்பட்டது',
    localStorageFallback: 'உள்ளூர் சேமிப்பகம் பயன்பாட்டில்',
    tableArtisans: 'கைவினைஞர்கள் (artisans)',
    tableProducts: 'தயாரிப்புகள் (products)',
    tableOrders: 'ஆர்டர்கள் (orders)',
    schemaDetails: 'தரவுத்தள திட்ட அமைப்பு',
  },
  en: {
    appTitle: 'Bharat TULIP Artisan Voice Studio',
    appSubtitle: 'Voice-First AI Market Linkage & Smart Cataloging for Artisans',
    voiceAssistant: 'Voice Assistant',
    askLanguage: 'Select your preferred regional language',
    tapToSpeak: 'Tap mic to speak',
    listening: 'Listening to your voice...',
    aiThinking: 'AI processing...',
    speaking: 'Speaking...',
    onboardingTitle: 'Artisan Voice Onboarding',
    askNamePrompt: 'Namaste! Please tell me your full name to get started.',
    askVillagePrompt: 'Wonderful! Which village or district are you from?',
    askCraftPrompt: 'What traditional craft or product do you create?',
    nameLabel: 'Artisan Name',
    villageLabel: 'Village / District',
    craftLabel: 'Craft Specialty',
    createAccountBtn: 'Create Account & Open Storefront',
    accountCreated: 'Artisan account created successfully!',
    sellPageTitle: 'List New Product (3 Voice Steps)',
    stepPhotoTitle: 'Step 1: Capture Product Photo',
    stepPhotoPrompt: 'Please take a clear photo of your handcrafted product with your camera.',
    stepPhotoAiEnhance: 'AI removes background and generates a studio photoshoot listing.',
    takePhotoBtn: 'Open Camera',
    uploadPhotoBtn: 'Upload Photo',
    originalPhoto: 'Raw Camera Photo',
    studioPhoto: 'AI Enhanced Studio Photoshoot',
    stepDescTitle: 'Step 2: Describe in Your Own Words',
    stepDescPrompt: 'Tell me about the materials, craft process, and heritage in your local dialect.',
    stepDescExample: '"Handmade clay terracotta vase fired in traditional kiln with organic earth dyes..."',
    stepDescAiEnhance: 'AI transforms your dialect into SEO catalog story & global buyer keywords.',
    stepPriceTitle: 'Step 3: What is Your Asking Price?',
    stepPricePrompt: 'State the price in Rupees you would like to earn from this craft.',
    stepPriceMarketCompare: 'AI benchmarks e-commerce marketplaces and calculates fair artisan margin.',
    suggestedPriceLabel: 'AI Recommended Market Price',
    yourPriceLabel: 'Your Price (₹)',
    fairPriceBadge: 'Fair Artisan Direct Margin Guarantee',
    reviewTitle: 'Step 4: Final AI Review & Submission',
    reviewPrompt: 'Your listing is ready with studio imagery and SEO copy. Confirm to publish!',
    publishBtn: 'Publish to Bharat TULIP Marketplace',
    publishing: 'Publishing to marketplace...',
    productPublishedSuccess: 'Congratulations! Your handcrafted product is now live for buyers.',
    viewInStorefront: 'View Live in Buyer Storefront',
    dashboardTitle: 'Artisan Seller Dashboard',
    totalSales: 'Total Sales Revenue',
    activeOrders: 'Active Orders',
    revenueTrends: 'Revenue Trends & Analytics',
    inventoryControl: 'Inventory & Stock Control',
    orderManagement: 'Order Fulfillment Management',
    filterAll: 'All Orders',
    filterPending: 'Pending',
    filterFulfilled: 'Fulfilled',
    filterCanceled: 'Canceled',
    stockInStock: 'In Stock',
    stockLow: 'Low Stock',
    stockOut: 'Out of Stock',
    quickPriceEdit: 'Quick Edit',
    saveChanges: 'Save',
    buyerStoreTitle: 'Bharat TULIP National Storefront',
    buyFromArtisan: 'Buy Direct from Rural Artisan',
    verifiedArtisan: 'Verified Craft Heritage',
    fairPriceGuarantee: '100% Handcrafted Authenticity',
    addToCart: 'Order Now (COD / UPI / Card)',
    orderPlaced: 'Order placed successfully! Artisan notified.',
    dbInspectorTitle: 'Supabase End-to-End Database Inspector',
    supabaseSynced: 'Supabase Synced',
    localStorageFallback: 'Local Synced DB Active',
    tableArtisans: 'Artisans Table',
    tableProducts: 'Products Table',
    tableOrders: 'Orders Table',
    schemaDetails: 'Database Schema & Live Records',
  },
  te: {
    appTitle: 'భారత్ ట్యులిప్ చేతివృత్తుల వేదిక',
    appSubtitle: 'వాయిస్ ద్వారా మీ ఉత్పత్తులను నేరుగా ఆన్‌లైన్‌లో విక్రయించండి',
    voiceAssistant: 'వాయిస్ అసిస్టెంట్',
    askLanguage: 'మీ ప్రాంతీయ భాషను ఎంచుకోండి',
    tapToSpeak: 'మాట్లాడటానికి మైక్ నొక్కండి',
    listening: 'నేను వింటున్నాను...',
    aiThinking: 'AI ఆలోచిస్తోంది...',
    speaking: 'మాట్లాడుతోంది...',
    onboardingTitle: 'చేతివృత్తుల కళాకారుల నమోదు',
    askNamePrompt: 'నమస్కారం! దయచేసి మీ పేరు చెప్పండి.',
    askVillagePrompt: 'చాలా బాగుంది! మీరు ఏ గ్రామం లేదా జిల్లాకు చెందినవారు?',
    askCraftPrompt: 'మీరు ఏ విధమైన చేతివృత్తి లేదా వస్తువులను తయారు చేస్తారు?',
    nameLabel: 'కళాకారుడి పేరు',
    villageLabel: 'గ్రామం / పట్టణం',
    craftLabel: 'చేతివృత్తి రకం',
    createAccountBtn: 'ఖాతా సృష్టించి ప్రారంభించండి',
    accountCreated: 'మీ ఖాతా విజయవంతంగా సృష్టించబడింది!',
    sellPageTitle: 'కొత్త ఉత్పత్తిని జోడించండి (3 దశలు)',
    stepPhotoTitle: 'దశ 1: ఉత్పత్తి ఫోటో తీయండి',
    stepPhotoPrompt: 'మీ ఉత్పత్తిని కెమెరాతో స్పష్టమైన ఫోటో తీయండి.',
    stepPhotoAiEnhance: 'AI బ్యాక్‌గ్రౌండ్‌ను తొలగించి స్టూడియో ఫోటోగా మారుస్తుంది.',
    takePhotoBtn: 'కెమెరా తెరవండి',
    uploadPhotoBtn: 'ఫోటో అప్‌లోడ్ చేయండి',
    originalPhoto: 'మీరు తీసిన ఫోటో',
    studioPhoto: 'AI స్టూడియో ఫోటో',
    stepDescTitle: 'దశ 2: మీ మాటల్లో వివరించండి',
    stepDescPrompt: 'మీరు దీనిని ఎలా తయారు చేసారో మీ స్వంత భాషలో చెప్పండి.',
    stepDescExample: '"ఈ మట్టి కుండను నేను చేతితో సహజసిద్ధమైన రంగులతో తయారు చేసాను..."',
    stepDescAiEnhance: 'AI మీ మాటలను ఆకర్షణీయమైన ఉత్పత్తి వివరణగా మారుస్తుంది.',
    stepPriceTitle: 'దశ 3: మీరు కోరుకునే ధర ఎంత?',
    stepPricePrompt: 'దీనికి ఎంత ధర పొందాలనుకుంటున్నారో చెప్పండి.',
    stepPriceMarketCompare: 'AI మార్కెట్ ధరలను సరిపోల్చి సరసమైన ధరను సూచిస్తుంది.',
    suggestedPriceLabel: 'AI సూచించిన మార్కెట్ ధర',
    yourPriceLabel: 'మీ ధర',
    fairPriceBadge: 'కళాకారుడి లాభ హామీ',
    reviewTitle: 'దశ 4: సమీక్ష & ప్రచురణ',
    reviewPrompt: 'అన్నీ సిద్ధంగా ఉన్నాయి! మార్కెట్‌లో ప్రచురించాలా?',
    publishBtn: 'మార్కెట్‌లో ప్రచురించండి',
    publishing: 'ప్రచురిస్తోంది...',
    productPublishedSuccess: 'అభినందనలు! మీ ఉత్పత్తి లైవ్‌లోకి వచ్చింది.',
    viewInStorefront: 'కొనుగోలుదారుల పేజీలో చూడండి',
    dashboardTitle: 'కళాకారుడి డాష్‌బోర్డ్',
    totalSales: 'మొత్తం అమ్మకాలు',
    activeOrders: 'యాక్టివ్ ఆర్డర్లు',
    revenueTrends: 'ఆదాయ విశ్లేషణ',
    inventoryControl: 'స్టాక్ మరియు ధరలు',
    orderManagement: 'ఆర్డర్ల నిర్వహణ',
    filterAll: 'అన్నీ',
    filterPending: 'పెండింగ్',
    filterFulfilled: 'పూర్తయినవి',
    filterCanceled: 'రద్దు చేయబడినవి',
    stockInStock: 'స్టాక్ ఉంది',
    stockLow: 'తక్కువ స్టాక్',
    stockOut: 'స్టాక్ అయిపోయింది',
    quickPriceEdit: 'ధర మార్చండి',
    saveChanges: 'సేవ్ చేయండి',
    buyerStoreTitle: 'భారత్ ట్యులిప్ మార్కెట్',
    buyFromArtisan: 'నేరుగా కళాకారుడి నుండి కొనండి',
    verifiedArtisan: 'ధృవీకరించబడిన కళాకారుడు',
    fairPriceGuarantee: '100% అసలైన చేతిపని',
    addToCart: 'ఇప్పుడే కొనండి',
    orderPlaced: 'ఆర్డర్ విజయవంతంగా నమోదైంది!',
    dbInspectorTitle: 'సుపాబేస్ డేటాబేస్ వీక్షకం',
    supabaseSynced: 'సుపాబేస్ అనుసంధానించబడింది',
    localStorageFallback: 'లోకల్ డేటాబేస్ సక్రియంగా ఉంది',
    tableArtisans: 'కళాకారులు (artisans)',
    tableProducts: 'ఉత్పత్తులు (products)',
    tableOrders: 'ఆర్డర్లు (orders)',
    schemaDetails: 'డేటాబేస్ స్కీమా రికార్డులు',
  },
  bn: {
    appTitle: 'ভারত টিউলিপ কারিগর সাথী',
    appSubtitle: 'কণ্ঠস্বরের মাধ্যমে সরাসরি আপনার শিল্পকর্ম অনলাইনে বিক্রি করুন',
    voiceAssistant: 'ভয়েস সহকারী',
    askLanguage: 'আপনার ভাষা নির্বাচন করুন',
    tapToSpeak: 'কথা বলতে মাইকে চাপ দিন',
    listening: 'শুনছি...',
    aiThinking: 'AI চিন্তা করছে...',
    speaking: 'বলছে...',
    onboardingTitle: 'কারিগর ভয়েস রেজিস্ট্রেশন',
    askNamePrompt: 'নমস্কার! দয়া করে আপনার সম্পূর্ণ নাম বলুন।',
    askVillagePrompt: 'খুব ভালো! আপনি কোন গ্রাম বা জেলার বাসিন্দা?',
    askCraftPrompt: 'আপনি কোন ঐতিহ্যবাহী হস্তশিল্প বা পণ্য তৈরি করেন?',
    nameLabel: 'কারিগরের নাম',
    villageLabel: 'গ্রাম / জেলা',
    craftLabel: 'হস্তশিল্পের ধরন',
    createAccountBtn: 'অ্যাকাউন্ট তৈরি করুন ও শুরু করুন',
    accountCreated: 'আপনার অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে!',
    sellPageTitle: 'নতুন পণ্য যোগ করুন (৩টি সহজ ধাপ)',
    stepPhotoTitle: 'ধাপ ১: পণ্যের ছবি তুলুন',
    stepPhotoPrompt: 'আপনার হস্তশিল্পের একটি পরিষ্কার ছবি তুলুন।',
    stepPhotoAiEnhance: 'AI ব্যাকগ্রাউন্ড সরিয়ে স্টুডিও মানের ছবি বানিয়ে দেবে।',
    takePhotoBtn: 'ক্যামেরা খুলুন',
    uploadPhotoBtn: 'ছবি আপলোড করুন',
    originalPhoto: 'আপনার তোলা ছবি',
    studioPhoto: 'AI স্টুডিও ফটো',
    stepDescTitle: 'ধাপ ২: নিজের ভাষায় বিবরণ দিন',
    stepDescPrompt: 'এটি আপনি কীভাবে তৈরি করেছেন তা আপনার নিজের ভাষায় বলুন।',
    stepDescExample: '"এই মাটির পাত্রটি আমি হাতে চাকের সাহায্যে তৈরি করেছি..."',
    stepDescAiEnhance: 'AI আপনার কথাকে একটি সুন্দর অনলাইন বর্ণনায় রূপান্তর করবে।',
    stepPriceTitle: 'ধাপ ৩: আপনি কত দাম চান?',
    stepPricePrompt: 'আপনি এটির জন্য কত দাম আশা করছেন তা বলুন।',
    stepPriceMarketCompare: 'AI বাজারের দাম যাচাই করে ন্যায্য মূল্য নির্ধারণে সাহায্য করবে।',
    suggestedPriceLabel: 'AI প্রস্তাবিত বাজার মূল্য',
    yourPriceLabel: 'আপনার দাম',
    fairPriceBadge: 'ন্যায্য লাভ গ্যারান্টি',
    reviewTitle: 'ধাপ ৪: পর্যালোচনা ও প্রকাশ',
    reviewPrompt: 'সব তৈরি! আপনি কি এটি বাজারে প্রকাশ করতে চান?',
    publishBtn: 'বাজারে প্রকাশ করুন',
    publishing: 'প্রকাশিত হচ্ছে...',
    productPublishedSuccess: 'অভিনন্দন! আপনার পণ্য অনলাইনে প্রকাশিত হয়েছে।',
    viewInStorefront: 'ক্রেতার পেজে দেখুন',
    dashboardTitle: 'কারিগর ড্যাশবোর্ড',
    totalSales: 'মোট বিক্রি',
    activeOrders: 'সক্রিয় অর্ডার',
    revenueTrends: 'আয়ের গ্রাফ',
    inventoryControl: 'স্টক ও পণ্য তালিকা',
    orderManagement: 'অর্ডার পরিচালনা',
    filterAll: 'সকল',
    filterPending: 'অপেক্ষমাণ',
    filterFulfilled: 'সম্পূর্ণ',
    filterCanceled: 'বাতিল',
    stockInStock: 'মজুদ আছে',
    stockLow: 'কম মজুদ',
    stockOut: 'শেষ',
    quickPriceEdit: 'দাম পরিবর্তন',
    saveChanges: 'সংরক্ষণ',
    buyerStoreTitle: 'ভারত টিউলিপ বাজার',
    buyFromArtisan: 'সরাসরি কারিগরের কাছ থেকে কিনুন',
    verifiedArtisan: 'যাচাইকৃত গ্রামীণ কারিগর',
    fairPriceGuarantee: '১০০% আসল হস্তশিল্প',
    addToCart: 'এখনই কিনুন',
    orderPlaced: 'অর্ডার সফলভাবে গ্রহণ করা হয়েছে!',
    dbInspectorTitle: 'সুপাবেস ডাটাবেজ ভিউয়ার',
    supabaseSynced: 'সুপাবেসের সাথে যুক্ত',
    localStorageFallback: 'স্থানীয় ডাটাবেজ সক্রিয়',
    tableArtisans: 'কারিগর তালিকা',
    tableProducts: 'পণ্য তালিকা',
    tableOrders: 'অর্ডার তালিকা',
    schemaDetails: 'ডাটাবেজ স্কিমা ও তথ্য',
  },
  mr: {
    appTitle: 'भारत ट्यूलिप कारागीर मंच',
    appSubtitle: 'आवाजाद्वारे आपली उत्पादने थेट ऑनलाइन विका',
    voiceAssistant: 'व्हॉईस सहाय्यक',
    askLanguage: 'कृपया तुमची प्रादेशिक भाषा निवडा',
    tapToSpeak: 'बोलण्यासाठी माइक दाबा',
    listening: 'मी ऐकत आहे...',
    aiThinking: 'AI विचार करत आहे...',
    speaking: 'बोलत आहे...',
    onboardingTitle: 'कारागीर नोंदणी (फक्त बोलून)',
    askNamePrompt: 'नमस्कार कारागीर जी! कृपया आपले पूर्ण नाव सांगा.',
    askVillagePrompt: 'छान! आपण कोणत्या गाव किंवा शहरातून आहात?',
    askCraftPrompt: 'आपण कोणती पारंपरिक हस्तकला किंवा वस्तू तयार करता?',
    nameLabel: 'कारागिराचे नाव',
    villageLabel: 'गाव / शहर',
    craftLabel: 'हस्तकला प्रकार',
    createAccountBtn: 'खाते तयार करा आणि सुरू करा',
    accountCreated: 'आपले खाते यशस्वीरित्या तयार झाले!',
    sellPageTitle: 'नवीन उत्पादन जोडा (३ सोपे टप्पे)',
    stepPhotoTitle: 'टप्पा १: उत्पादनाचा फोटो घ्या',
    stepPhotoPrompt: 'आपल्या हस्तकलेचा एक स्पष्ट फोटो कॅमेऱ्याने घ्या.',
    stepPhotoAiEnhance: 'AI पार्श्वभूमी काढून स्टुडिओ फोटो तयार करेल.',
    takePhotoBtn: 'कॅमेरा उघडा',
    uploadPhotoBtn: 'फोटो अपलोड करा',
    originalPhoto: 'आपण घेतलेला फोटो',
    studioPhoto: 'AI स्टुडिओ फोटो',
    stepDescTitle: 'टप्पा २: उत्पादनाबद्दल बोलून सांगा',
    stepDescPrompt: 'हे आपण कसे बनवले ते आपल्या भाषेत सांगा.',
    stepDescExample: '"हे मातीचे भांडे मी चाकावर हाताने तयार केले आहे..."',
    stepDescAiEnhance: 'AI आपले शब्द ऑनलाइन ग्राहकांसाठी आकर्षक बनवेल.',
    stepPriceTitle: 'टप्पा ३: आपल्याला काय किंमत हवी आहे?',
    stepPricePrompt: 'आपण याची काय किंमत ठेवू इच्छिता ते सांगा.',
    stepPriceMarketCompare: 'AI बाजारातील किमतींशी तुलना करून योग्य किंमत सुचवेल.',
    suggestedPriceLabel: 'AI शिफारस केलेली किंमत',
    yourPriceLabel: 'आपली किंमत',
    fairPriceBadge: 'योग्य नफा हमी',
    reviewTitle: 'टप्पा ४: पुनरावलोकन आणि प्रकाशन',
    reviewPrompt: 'सर्व तयार आहे! बाजारात प्रकाशित करायचे का?',
    publishBtn: 'बाजारात प्रकाशित करा',
    publishing: 'प्रकाशित होत आहे...',
    productPublishedSuccess: 'अभिनंदन! आपले उत्पादन थेट विक्रीसाठी उपलब्ध झाले आहे.',
    viewInStorefront: 'खरेदीदाराच्या दुकानात पहा',
    dashboardTitle: 'कारागीर डॅशबोर्ड',
    totalSales: 'एकूण विक्री उत्पन्न',
    activeOrders: 'सक्रिय ऑर्डर्स',
    revenueTrends: 'उत्पन्न विश्लेषण',
    inventoryControl: 'साठा आणि उत्पादने',
    orderManagement: 'ऑर्डर व्यवस्थापन',
    filterAll: 'सर्व',
    filterPending: 'प्रलंबित',
    filterFulfilled: 'पूर्ण',
    filterCanceled: 'रद्द',
    stockInStock: 'उपलब्ध',
    stockLow: 'कमी साठा',
    stockOut: 'संपले',
    quickPriceEdit: 'किंमत बदला',
    saveChanges: 'जतन करा',
    buyerStoreTitle: 'भारत ट्यूलिप बाजार',
    buyFromArtisan: 'थेट ग्रामीण कारागिराकडून खरेदी करा',
    verifiedArtisan: 'प्रमाणित हस्तकला',
    fairPriceGuarantee: '१००% अस्सल हस्तकला',
    addToCart: 'आत्ताच खरेदी करा',
    orderPlaced: 'ऑर्डर यशस्वीरित्या नोंदवली गेली!',
    dbInspectorTitle: 'सुपाबेस डेटाबेस व्ह्यूअर',
    supabaseSynced: 'सुपाबेसशी जोडलेले',
    localStorageFallback: 'स्थानिक डेटाबेस चालू आहे',
    tableArtisans: 'कारागीर तक्ता',
    tableProducts: 'उत्पादने तक्ता',
    tableOrders: 'ऑर्डर्स तक्ता',
    schemaDetails: 'डेटाबेस स्कीमा आणि नोंदी',
  },
  gu: {
    appTitle: 'ભારત ટ્યૂલિપ કારીગર મંચ',
    appSubtitle: 'તમારા અવાજ દ્વારા તમારી હસ્તકલા સીધી ઑનલાઇન વેચો',
    voiceAssistant: 'વૉઇસ સહાયક',
    askLanguage: 'કૃપા કરીને તમારી પ્રાદેશિક ભાષા પસંદ કરો',
    tapToSpeak: 'બોલવા માટે માઇક દબાવો',
    listening: 'હું સાંભળી રહી છું...',
    aiThinking: 'AI વિચારી રહ્યું છે...',
    speaking: 'બોલી રહ્યું છે...',
    onboardingTitle: 'કારીગર વૉઇસ રજિસ્ટ્રેશન',
    askNamePrompt: 'નમસ્તે કારીગર જી! કૃપા કરીને તમારું પૂરું નામ કહો.',
    askVillagePrompt: 'ખૂબ સરસ! તમે કયા ગામ કે શહેરથી છો?',
    askCraftPrompt: 'તમે કઈ પરંપરાગત હસ્તકલા કે ઉત્પાદન બનાવો છો?',
    nameLabel: 'કારીગરનું નામ',
    villageLabel: 'ગામ / શહેર',
    craftLabel: 'હસ્તકલાનો પ્રકાર',
    createAccountBtn: 'ખાતું બનાવો અને શરૂ કરો',
    accountCreated: 'તમારું ખાતું સફળતાપૂર્વક બની ગયું છે!',
    sellPageTitle: 'નવું ઉત્પાદન ઉમેરો (૩ સરળ પગલાં)',
    stepPhotoTitle: 'પગલું ૧: ઉત્પાદનનો ફોટો લો',
    stepPhotoPrompt: 'તમારી હસ્તકલાનો સ્પષ્ટ ફોટો કૅમેરાથી ખેંચો.',
    stepPhotoAiEnhance: 'AI બેકગ્રાઉન્ડ હટાવીને સ્ટુડિયો ફોટો બનાવી દેશે.',
    takePhotoBtn: 'કૅમેરા ખોલો',
    uploadPhotoBtn: 'ફોટો અપલોડ કરો',
    originalPhoto: 'તમારો લીધેલો ફોટો',
    studioPhoto: 'AI સ્ટુડિયો ફોટો',
    stepDescTitle: 'પગલું ૨: તમારા શબ્દોમાં વર્ણન કરો',
    stepDescPrompt: 'આ તમે કેવી રીતે બનાવ્યું તે તમારી ભાષામાં બોલીને જણાવો.',
    stepDescExample: '"આ માટીનો કૂંજો મેં ચાક પર હાથેથી બનાવ્યો છે..."',
    stepDescAiEnhance: 'AI તમારા શબ્દોને સુંદર વેચાણ વિગતોમાં ફેરવી દેશે.',
    stepPriceTitle: 'પગલું ૩: તમે શું કિંમત મેળવવા માંગો છો?',
    stepPricePrompt: 'તમે આના કેટલા રૂપિયા લેવા માંગો છો તે જણાવો.',
    stepPriceMarketCompare: 'AI બજાર કિંમતો સાથે સરખામણી કરીને યોગ્ય કિંમત સૂચવશે.',
    suggestedPriceLabel: 'AI ભલામણ કરેલ બજાર કિંમત',
    yourPriceLabel: 'તમારી કિંમત',
    fairPriceBadge: 'યોગ્ય નફો ગેરંટી',
    reviewTitle: 'પગલું ૪: સમીક્ષા અને પ્રકાશન',
    reviewPrompt: 'બધું તૈયાર છે! બજારમાં પ્રકાશિત કરીએ?',
    publishBtn: 'બજારમાં વેચાણ માટે મૂકો',
    publishing: 'પ્રકાશિત થઈ રહ્યું છે...',
    productPublishedSuccess: 'અભિનંદન! તમારું ઉત્પાદન લાઈવ થઈ ગયું છે.',
    viewInStorefront: 'ગ્રાહક સ્ટોરમાં જુઓ',
    dashboardTitle: 'કારીગર ડેશબોર્ડ',
    totalSales: 'કુલ વેચાણ આવક',
    activeOrders: 'સક્રિય ઓર્ડર્સ',
    revenueTrends: 'આવક વલણ',
    inventoryControl: 'સ્ટોક અને ઉત્પાદન યાદી',
    orderManagement: 'ઓર્ડર વ્યવસ્થાપન',
    filterAll: 'બધા',
    filterPending: 'બાકી',
    filterFulfilled: 'પૂર્ણ થયેલ',
    filterCanceled: 'રદ થયેલ',
    stockInStock: 'સ્ટોકમાં છે',
    stockLow: 'ઓછો સ્ટોક',
    stockOut: 'ખલાસ',
    quickPriceEdit: 'કિંમત બદલો',
    saveChanges: 'સાચવો',
    buyerStoreTitle: 'ભારત ટ્યૂલિપ માર્કેટ',
    buyFromArtisan: 'સીધા ગ્રામીણ કારીગર પાસેથી ખરીદો',
    verifiedArtisan: 'પ્રમાણિત કારીગર',
    fairPriceGuarantee: '૧૦૦% અસલી હસ્તકલા',
    addToCart: 'હમણાં જ ખરીદો',
    orderPlaced: 'ઓર્ડર સફળતાપૂર્વક નોંધાયો!',
    dbInspectorTitle: 'સુપાબેસ ડેટાબેઝ દર્શક',
    supabaseSynced: 'સુપાબેસ સાથે જોડાયેલ',
    localStorageFallback: 'સ્થાનિક ડેટાબેઝ સક્રિય',
    tableArtisans: 'કારીગરોનું કોષ્ટક',
    tableProducts: 'ઉત્પાદનોનું કોષ્ટક',
    tableOrders: 'ઓર્ડર્સનું કોષ્ટક',
    schemaDetails: 'ડેટાબેઝ સ્કીમા વિગતો',
  },
  kn: {
    appTitle: 'ಭಾರತ ಟುಲಿಪ್ ಕುಶಲಕರ್ಮಿ ವೇದಿಕೆ',
    appSubtitle: 'ಧ್ವನಿಯ ಮೂಲಕ ನಿಮ್ಮ ಕರಕುಶಲ ವಸ್ತುಗಳನ್ನು ನೇರವಾಗಿ ಮಾರಾಟ ಮಾಡಿ',
    voiceAssistant: 'ವಾಯ್ಸ್ ಸಹಾಯಕ',
    askLanguage: 'ನಿಮ್ಮ ಪ್ರಾದೇಶಿಕ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    tapToSpeak: 'ಮಾತನಾಡಲು ಮೈಕ್ ಒತ್ತಿ',
    listening: 'ನಾನು ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದೇನೆ...',
    aiThinking: 'AI ಯೋಚಿಸುತ್ತಿದೆ...',
    speaking: 'ಮಾತನಾಡುತ್ತಿದೆ...',
    onboardingTitle: 'ಕುಶಲಕರ್ಮಿ ಧ್ವನಿ ನೋಂದಣಿ',
    askNamePrompt: 'ನಮಸ್ಕಾರ! ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ಹೇಳಿ.',
    askVillagePrompt: 'ಉತ್ತಮ! ನೀವು ಯಾವ ಊರು ಅಥವಾ ಜಿಲ್ಲೆಯವರು?',
    askCraftPrompt: 'ನೀವು ಯಾವ ಸಾಂಪ್ರದಾಯಿಕ ಕರಕುಶಲ ವಸ್ತುಗಳನ್ನು ತಯಾರಿಸುತ್ತೀರಿ?',
    nameLabel: 'ಕುಶಲಕರ್ಮಿಯ ಹೆಸರು',
    villageLabel: 'ಊರು / ಜಿಲ್ಲೆ',
    craftLabel: 'ಕರಕುಶಲ ಪ್ರಕಾರ',
    createAccountBtn: 'ಖಾತೆ ತೆರೆದು ಪ್ರಾರಂಭಿಸಿ',
    accountCreated: 'ನಿಮ್ಮ ಖಾತೆ ಯಶಸ್ವಿಯಾಗಿ ರಚನೆಯಾಗಿದೆ!',
    sellPageTitle: 'ಹೊಸ ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ (೩ ಸರಳ ಹಂತಗಳು)',
    stepPhotoTitle: 'ಹಂತ ೧: ಉತ್ಪನ್ನದ ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ',
    stepPhotoPrompt: 'ನಿಮ್ಮ ಕರಕುಶಲ ವಸ್ತುವಿನ ಸ್ಪಷ್ಟ ಫೋಟೋವನ್ನು ಕ್ಯಾಮೆರಾದಲ್ಲಿ ತೆಗೆಯಿರಿ.',
    stepPhotoAiEnhance: 'AI ಹಿನ್ನೆಲೆಯನ್ನು ತೆಗೆದು ಸ್ಟುಡಿಯೋ ಫೋಟೋವಾಗಿ ಬದಲಾಯಿಸುತ್ತದೆ.',
    takePhotoBtn: 'ಕ್ಯಾಮೆರಾ ತೆರೆಯಿರಿ',
    uploadPhotoBtn: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    originalPhoto: 'ನೀವು ತೆಗೆದ ಫೋಟೋ',
    studioPhoto: 'AI ಸ್ಟುಡಿಯೋ ಫೋಟೋ',
    stepDescTitle: 'ಹಂತ ೨: ನಿಮ್ಮ ಮಾತಿನಲ್ಲಿ ವಿವರಿಸಿ',
    stepDescPrompt: 'ಇದನ್ನು ನೀವು ಹೇಗೆ ತಯಾರಿಸಿದ್ದೀರಿ ಎಂದು ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಹೇಳಿ.',
    stepDescExample: '"ಈ ಮಣ್ಣಿನ ಪಾತ್ರೆಯನ್ನು ನಾನು ಕೈಯಿಂದ ಸಾಂಪ್ರದಾಯಿಕವಾಗಿ ತಯಾರಿಸಿದ್ದೇನೆ..."',
    stepDescAiEnhance: 'AI ಇದನ್ನು ಆಕರ್ಷಕ ಮಾರಾಟ ವಿವರಣೆಯಾಗಿ ಪರಿವರ್ತಿಸುತ್ತದೆ.',
    stepPriceTitle: 'ಹಂತ ೩: ನೀವು ಬಯಸುವ ಬೆಲೆ ಎಷ್ಟು?',
    stepPricePrompt: 'ಇದಕ್ಕೆ ನೀವು ಎಷ್ಟು ಬೆಲೆ ನಿಗದಿಪಡಿಸಲು ಬಯಸುತ್ತೀರಿ ಹೇಳಿ.',
    stepPriceMarketCompare: 'AI ಮಾರುಕಟ್ಟೆ ಬೆಲೆಯನ್ನು ಹೋಲಿಸಿ ನ್ಯಾಯಯುತ ಬೆಲೆಯನ್ನು ಸೂಚಿಸುತ್ತದೆ.',
    suggestedPriceLabel: 'AI ಶಿಫಾರಸು ಮಾಡಿದ ಬೆಲೆ',
    yourPriceLabel: 'ನಿಮ್ಮ ಬೆಲೆ',
    fairPriceBadge: 'ನ್ಯಾಯಯುತ ಲಾಭದ ಭರವಸೆ',
    reviewTitle: 'ಹಂತ ೪: ಪರಿಶೀಲನೆ & ಪ್ರಕಟಣೆ',
    reviewPrompt: 'ಎಲ್ಲವೂ ಸಿದ್ಧವಾಗಿದೆ! ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಪ್ರಕಟಿಸೋಣವೇ?',
    publishBtn: 'ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಪ್ರಕಟಿಸಿ',
    publishing: 'ಪ್ರಕಟಿಸಲಾಗುತ್ತಿದೆ...',
    productPublishedSuccess: 'ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಉತ್ಪನ್ನ ನೇರ ಮಾರಾಟಕ್ಕೆ ಲಭ್ಯವಿದೆ.',
    viewInStorefront: 'ಗ್ರಾಹಕರ ಅಂಗಡಿಯಲ್ಲಿ ನೋಡಿ',
    dashboardTitle: 'ಕುಶಲಕರ್ಮಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    totalSales: 'ಒಟ್ಟು ಮಾರಾಟ',
    activeOrders: 'ಸಕ್ರಿಯ ಆದೇಶಗಳು',
    revenueTrends: 'ಆದಾಯದ ಅಂಕಿಅಂಶ',
    inventoryControl: 'ದಾಸ್ತಾನು ಮತ್ತು ಉತ್ಪನ್ನಗಳು',
    orderManagement: 'ಆದೇಶ ನಿರ್ವಹಣೆ',
    filterAll: 'ಎಲ್ಲಾ',
    filterPending: 'ಬಾಕಿ ಇರುವ',
    filterFulfilled: 'ಪೂರ್ಣಗೊಂಡ',
    filterCanceled: 'ರದ್ದುಗೊಂಡ',
    stockInStock: 'ಲಭ್ಯವಿದೆ',
    stockLow: 'ಕಡಿಮೆ ದಾಸ್ತಾನು',
    stockOut: 'ಖಾಲಿಯಾಗಿದೆ',
    quickPriceEdit: 'ಬೆಲೆ ಬದಲಾಯಿಸಿ',
    saveChanges: 'ಉಳಿಸಿ',
    buyerStoreTitle: 'ಭಾರತ ಟುಲಿಪ್ ಮಾರುಕಟ್ಟೆ',
    buyFromArtisan: 'ನೇರವಾಗಿ ಗ್ರಾಮೀಣ ಕುಶಲಕರ್ಮಿಯಿಂದ ಖರೀದಿಸಿ',
    verifiedArtisan: 'ದೃಢೀಕೃತ ಕುಶಲಕರ್ಮಿ',
    fairPriceGuarantee: '೧೦೦% ನೈಜ ಕರಕುಶಲ ವಸ್ತು',
    addToCart: 'ಈಗಲೇ ಖರೀದಿಸಿ',
    orderPlaced: 'ಆದೇಶ ಯಶಸ್ವಿಯಾಗಿ ದಾಖಲಾಗಿದೆ!',
    dbInspectorTitle: 'ಸುಪಬೇಸ್ ಡೇಟಾಬೇಸ್ ವೀಕ್ಷಕ',
    supabaseSynced: 'ಸುಪಬೇಸ್‌ಗೆ ಸಿಂಕ್ ಆಗಿದೆ',
    localStorageFallback: 'ಸ್ಥಳೀಯ ಡೇಟಾಬೇಸ್ ಚಾಲ್ತಿಯಲ್ಲಿದೆ',
    tableArtisans: 'ಕುಶಲಕರ್ಮಿಗಳ ಪಟ್ಟಿ',
    tableProducts: 'ಉತ್ಪನ್ನಗಳ ಪಟ್ಟಿ',
    tableOrders: 'ಆದೇಶಗಳ ಪಟ್ಟಿ',
    schemaDetails: 'ಡೇಟಾಬೇಸ್ ವಿವರಗಳು',
  },
  ml: {
    appTitle: 'ഭാരത് ട്യൂലിപ് കരകൗശല സഹായി',
    appSubtitle: 'ശബ്ദത്തിലൂടെ നിങ്ങളുടെ കരകൗശല വസ്തുക്കൾ നേരിട്ട് വിൽക്കുക',
    voiceAssistant: 'വോയ്സ് അസിസ്റ്റന്റ്',
    askLanguage: 'നിങ്ങളുടെ പ്രാദേശിക ഭാഷ തിരഞ്ഞെടുക്കുക',
    tapToSpeak: 'സംസാരിക്കാൻ മൈക്ക് അമർത്തുക',
    listening: 'കേൾക്കുന്നു...',
    aiThinking: 'AI ചിന്തിക്കുന്നു...',
    speaking: 'സംസാരിക്കുന്നു...',
    onboardingTitle: 'കരകൗശല വിദഗ്ദ്ധന്റെ ശബ്ദ രജിസ്ട്രേഷൻ',
    askNamePrompt: 'നമസ്കാരം! ദയവായി നിങ്ങളുടെ പൂർണ്ണ പേര് പറയൂ.',
    askVillagePrompt: 'വളരെ നല്ലത്! നിങ്ങൾ ഏത് നാട്ടുകാരനാണ്?',
    askCraftPrompt: 'നിങ്ങൾ എന്ത് പരമ്പരാഗത കരകൗശല വസ്തുവാണ് ഉണ്ടാക്കുന്നത്?',
    nameLabel: 'പേര്',
    villageLabel: 'നാട് / ജില്ല',
    craftLabel: 'കരകൗശല വിദ്യ',
    createAccountBtn: 'അക്കൗണ്ട് സൃഷ്ടിച്ച് ആരംഭിക്കുക',
    accountCreated: 'നിങ്ങളുടെ അക്കൗണ്ട് വിജയകരമായി സൃഷ്ടിച്ചു!',
    sellPageTitle: 'പുതിയ ഉൽപ്പന്നം ചേർക്കുക (3 ലളിതമായ ഘട്ടങ്ങൾ)',
    stepPhotoTitle: 'ഘട്ടം 1: ഉൽപ്പന്നത്തിന്റെ ഫോട്ടോ എടുക്കുക',
    stepPhotoPrompt: 'നിങ്ങളുടെ കരകൗശല വസ്തുവിന്റെ വ്യക്തമായ ഫോട്ടോ എടുക്കുക.',
    stepPhotoAiEnhance: 'AI പശ്ചാത്തലം മാറ്റി സ്റ്റുഡിയോ ഫോട്ടോയാക്കി മാറ്റും.',
    takePhotoBtn: 'ക്യാമറ തുറക്കുക',
    uploadPhotoBtn: 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
    originalPhoto: 'നിങ്ങൾ എടുത്ത ഫോട്ടോ',
    studioPhoto: 'AI സ്റ്റുഡിയോ ഫോട്ടോ',
    stepDescTitle: 'ഘട്ടം 2: ഉൽപ്പന്നത്തെക്കുറിച്ച് വിവരിക്കുക',
    stepDescPrompt: 'ഇത് നിങ്ങൾ എങ്ങനെ ഉണ്ടാക്കി എന്ന് നിങ്ങളുടെ സ്വന്തം ഭാഷയിൽ പറയൂ.',
    stepDescExample: '"ഈ മൺപാത്രം ഞാൻ പരമ്പരാഗത രീതിയിൽ കൈകൊണ്ട് നിർമ്മിച്ചതാണ്..."',
    stepDescAiEnhance: 'AI ഇതിനെ ആകർഷകമായ വിൽപ്പന വിവരണമാക്കി മാറ്റും.',
    stepPriceTitle: 'ഘട്ടം 3: നിങ്ങൾക്ക് എത്ര രൂപ ലഭിക്കണം?',
    stepPricePrompt: 'ഇതിന് എത്ര വിലയാണ് നിങ്ങൾ പ്രതീക്ഷിക്കുന്നത് എന്ന് പറയൂ.',
    stepPriceMarketCompare: 'AI വിപണി വിലയുമായി താരതമ്യം ചെയ്ത് ന്യായവില നിർദ്ദേശിക്കും.',
    suggestedPriceLabel: 'AI നിർദ്ദേശിച്ച വിപണി വില',
    yourPriceLabel: 'നിങ്ങളുടെ വില',
    fairPriceBadge: 'ന്യായമായ വരുമാന ഉറപ്പ്',
    reviewTitle: 'ഘട്ടം 4: വിലയിരുത്തലും പ്രസിദ്ധീകരണവും',
    reviewPrompt: 'എല്ലാം തയ്യാറാണ്! വിപണിയിൽ പ്രസിദ്ധീകരിക്കാമോ?',
    publishBtn: 'വിപണിയിൽ പ്രസിദ്ധീകരിക്കുക',
    publishing: 'പ്രസിദ്ധീകരിക്കുന്നു...',
    productPublishedSuccess: 'അഭിനന്ദനങ്ങൾ! നിങ്ങളുടെ ഉൽപ്പന്നം വിൽപ്പനയ്ക്ക് സജ്ജമായി.',
    viewInStorefront: 'ഉപഭോക്തൃ സ്റ്റോറിൽ കാണുക',
    dashboardTitle: 'കരകൗശല ഡാഷ്‌ബോർഡ്',
    totalSales: 'ആകെ വിറ്റുവരവ്',
    activeOrders: 'സജീവ ഓർഡറുകൾ',
    revenueTrends: 'വരുമാന വിശകലനം',
    inventoryControl: 'സ്റ്റോക്കും ഉൽപ്പന്നങ്ങളും',
    orderManagement: 'ഓർഡർ മാനേജ്മെന്റ്',
    filterAll: 'എല്ലാം',
    filterPending: 'തീർപ്പാക്കാത്തവ',
    filterFulfilled: 'പൂർത്തിയായവ',
    filterCanceled: 'റദ്ദാക്കിയവ',
    stockInStock: 'സ്റ്റോക്കുണ്ട്',
    stockLow: 'കുറഞ്ഞ സ്റ്റോക്ക്',
    stockOut: 'തീർന്നു',
    quickPriceEdit: 'വില മാറ്റുക',
    saveChanges: 'സേവ് ചെയ്യുക',
    buyerStoreTitle: 'ഭാരത് ട്യൂലിപ് മാർക്കറ്റ്',
    buyFromArtisan: 'നേരിട്ട് കരകൗശല തൊഴിലാളിയിൽ നിന്ന് വാങ്ങുക',
    verifiedArtisan: 'സാക്ഷ്യപ്പെടുത്തിയ കരകൗശല വിദഗ്ദ്ധൻ',
    fairPriceGuarantee: '100% യഥാർത്ഥ കരകൗശല ഉൽപ്പന്നം',
    addToCart: 'ഇപ്പോൾ തന്നെ വാങ്ങുക',
    orderPlaced: 'ഓർഡർ വിജയകരമായി രേഖപ്പെടുത്തി!',
    dbInspectorTitle: 'സുപാബേസ് ഡാറ്റാബേസ് കാഴ്ച',
    supabaseSynced: 'സുപാബേസുമായി ബന്ധിപ്പിച്ചിരിക്കുന്നു',
    localStorageFallback: 'പ്രാദേശിക ഡാറ്റാബേസ് സജീവം',
    tableArtisans: 'കരകൗശല തൊഴിലാളികൾ',
    tableProducts: 'ഉൽപ്പന്നങ്ങൾ',
    tableOrders: 'ഓർഡറുകൾ',
    schemaDetails: 'ഡാറ്റാബേസ് വിവരങ്ങൾ',
  },
  or: {
    appTitle: 'ଭାରତ ଟିଉଲିପ୍ କାରିଗର ସାଥୀ',
    appSubtitle: 'ନିଜ ସ୍ୱରରେ ଅନଲାଇନ୍ ଦୋକାନ ଖୋଲନ୍ତୁ ଏବଂ ଆୟ ବୃଦ୍ଧି କରନ୍ତୁ',
    voiceAssistant: 'ଭଏସ୍ ସହାୟକ',
    askLanguage: 'ଦୟାକରି ଆପଣଙ୍କ ଭାଷା ଚୟନ କରନ୍ତୁ',
    tapToSpeak: 'କହିବା ପାଇଁ ମାଇକ୍ ଦବାନ୍ତୁ',
    listening: 'ମୁଁ ଶୁଣୁଛି...',
    aiThinking: 'AI ଭାବୁଛି...',
    speaking: 'କହୁଛି...',
    onboardingTitle: 'କାରିଗର ପଞ୍ଜୀକରଣ (ସ୍ୱର ମାଧ୍ୟମରେ)',
    askNamePrompt: 'ନମସ୍କାର! ଦୟାକରି ଆପଣଙ୍କ ନାମ କୁହନ୍ତୁ।',
    askVillagePrompt: 'ବହୁତ ଭଲ! ଆପଣ କେଉଁ ଗାଁ ବା ସହରରୁ ଆସିଛନ୍ତି?',
    askCraftPrompt: 'ଆପଣ କେଉଁ ପାରମ୍ପରିକ ହସ୍ତଶିଳ୍ପ ତିଆରି କରନ୍ତି?',
    nameLabel: 'କାରିଗରଙ୍କ ନାମ',
    villageLabel: 'ଗାଁ / ସହର',
    craftLabel: 'ହସ୍ତକଳା ପ୍ରକାର',
    createAccountBtn: 'ଖାତା ତିଆରି କରନ୍ତୁ ଓ ଆରମ୍ଭ କରନ୍ତୁ',
    accountCreated: 'ଆପଣଙ୍କ ଖାତା ସଫଳତାର ସହ ତିଆରି ହୋଇଛି!',
    sellPageTitle: 'ନୂତନ ଉତ୍ପାଦ ଯୋଡନ୍ତୁ (୩ଟି ସହଜ ପଦକ୍ଷେପ)',
    stepPhotoTitle: 'ପଦକ୍ଷେପ ୧: ଉତ୍ପାଦର ଫଟୋ ଉଠାନ୍ତୁ',
    stepPhotoPrompt: 'ଆପଣଙ୍କ ହସ୍ତଶିଳ୍ପର ଏକ ସ୍ପଷ୍ଟ ଫଟୋ କ୍ୟାମେରାରେ ଉଠାନ୍ତୁ।',
    stepPhotoAiEnhance: 'AI ପଛଭୂମି ହଟାଇ ଏହାକୁ ଷ୍ଟୁଡିଓ ଫଟୋରେ ବଦଳାଇବ।',
    takePhotoBtn: 'କ୍ୟାମେରା ଖୋଲନ୍ତୁ',
    uploadPhotoBtn: 'ଫଟୋ ଅପଲୋଡ କରନ୍ତୁ',
    originalPhoto: 'ଆପଣ ଉଠାଇଥିବା ଫଟୋ',
    studioPhoto: 'AI ଷ୍ଟୁଡିଓ ଫଟୋ',
    stepDescTitle: 'ପଦକ୍ଷେପ ୨: ନିଜ ଭାଷାରେ ବର୍ଣ୍ଣନା କରନ୍ତୁ',
    stepDescPrompt: 'ଏହା ଆପଣ କିପରି ତିଆରି କଲେ ତାହା କୁହନ୍ତୁ।',
    stepDescExample: '"ଏହି ମାଟି ପାତ୍ରଟି ମୁଁ ଚକ ଉପରେ ହାତରେ ତିଆରି କରିଛି..."',
    stepDescAiEnhance: 'AI ଏହାକୁ ଏକ ସୁନ୍ଦର ବିକ୍ରୟ ବିବରଣୀରେ ରୂପାନ୍ତରିତ କରିବ।',
    stepPriceTitle: 'ପଦକ୍ଷେପ ୩: ଆପଣ କେତେ ମୂଲ୍ୟ ଚାହାଁନ୍ତି?',
    stepPricePrompt: 'ଏହା ଆପଣ କେତେ ଟଙ୍କାରେ ବିକ୍ରି କରିବାକୁ ଚାହାଁନ୍ତି କୁହନ୍ତୁ।',
    stepPriceMarketCompare: 'AI ବଜାର ଦର ଯାଞ୍ଚ କରି ଉଚିତ ମୂଲ୍ୟ ସ୍ଥିର କରିବାରେ ସାହାଯ୍ୟ କରିବ।',
    suggestedPriceLabel: 'AI ପ୍ରସ୍ତାବିତ ବଜାର ଦର',
    yourPriceLabel: 'ଆପଣଙ୍କ ମୂଲ୍ୟ',
    fairPriceBadge: 'ଉଚିତ ଲାଭ ପ୍ରତିଶ୍ରୁତି',
    reviewTitle: 'ପଦକ୍ଷେପ ୪: ପୁନର୍ନିରୀକ୍ଷଣ ଏବଂ ପ୍ରକାଶନ',
    reviewPrompt: 'ସବୁକିଛି ପ୍ରସ୍ତୁତ! ଆପଣ ଏହାକୁ ବଜାରରେ ପ୍ରକାଶ କରିବାକୁ ଚାହାଁନ୍ତି କି?',
    publishBtn: 'ବଜାରରେ ପ୍ରକାଶ କରନ୍ତୁ',
    publishing: 'ପ୍ରକାଶିତ ହେଉଛି...',
    productPublishedSuccess: 'ଅଭିନନ୍ଦନ! ଆପଣଙ୍କ ଉତ୍ପାଦ ବଜାରରେ ଉପଲବ୍ଧ ହୋଇଛି।',
    viewInStorefront: 'ଗ୍ରାହକ ଦୋକାନରେ ଦେଖନ୍ତୁ',
    dashboardTitle: 'କାରିଗର ଡ୍ୟାସବୋର୍ଡ',
    totalSales: 'ମୋଟ ବିକ୍ରୟ',
    activeOrders: 'ସକ୍ରିୟ ଅର୍ଡର',
    revenueTrends: 'ଆୟ ବିଶ୍ଳେଷଣ',
    inventoryControl: 'ଷ୍ଟକ୍ ଏବଂ ଉତ୍ପାଦ ତାଲିକା',
    orderManagement: 'ଅର୍ଡର ପରିଚାଳନା',
    filterAll: 'ସମସ୍ତ',
    filterPending: 'ଅପେକ୍ଷାରତ',
    filterFulfilled: 'ସମ୍ପୂର୍ଣ୍ଣ',
    filterCanceled: 'ବାତିଲ୍',
    stockInStock: 'ମହଜୁଦ ଅଛି',
    stockLow: 'କମ୍ ଷ୍ଟକ୍',
    stockOut: 'ଶେଷ',
    quickPriceEdit: 'ମୂଲ୍ୟ ପରିବର୍ତ୍ତନ',
    saveChanges: 'ସଂରକ୍ଷଣ କରନ୍ତୁ',
    buyerStoreTitle: 'ଭାରତ ଟିଉଲିପ୍ ବଜାର',
    buyFromArtisan: 'ସିଧାସଳଖ କାରିଗରଙ୍କ ଠାରୁ କିଣନ୍ତୁ',
    verifiedArtisan: 'ଯାଞ୍ଚ ହୋଇଥିବା କାରିଗର',
    fairPriceGuarantee: '୧୦୦% ପ୍ରାମାଣିକ ହସ୍ତଶିଳ୍ପ',
    addToCart: 'ଏବେ କିଣନ୍ତୁ',
    orderPlaced: 'ଅର୍ଡର ସଫଳତାର ସହିତ ଗ୍ରହଣ କରାଯାଇଛି!',
    dbInspectorTitle: 'ସୁପାବେସ୍ ଡାଟାବେସ୍ ପ୍ରଦର୍ଶକ',
    supabaseSynced: 'ସୁପାବେସ୍ ସହ ସଂଯୁକ୍ତ',
    localStorageFallback: 'ସ୍ଥାନୀୟ ଡାଟାବେସ୍ ସକ୍ରିୟ',
    tableArtisans: 'କାରିଗର ତାଲିକା',
    tableProducts: 'ଉତ୍ପାଦ ତାଲିକା',
    tableOrders: 'ଅର୍ଡର ତାଲିକା',
    schemaDetails: 'ଡାଟାବେସ୍ ସ୍କିମା ରେକର୍ଡ',
  },
  pa: {
    appTitle: 'ਭਾਰਤ ਟਿਊਲਿਪ ਦਸਤਕਾਰ ਮੰਚ',
    appSubtitle: 'ਆਪਣੀ ਆਵਾਜ਼ ਨਾਲ ਆਨਲਾਈਨ ਸਟੋਰ ਬਣਾਓ ਅਤੇ ਕਮਾਈ ਵਧਾਓ',
    voiceAssistant: 'ਵਾਇਸ ਸਹਾਇਕ',
    askLanguage: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਬੋਲੀ ਚੁਣੋ',
    tapToSpeak: 'ਬੋਲਣ ਲਈ ਮਾਈਕ ਦਬਾਓ',
    listening: 'ਸੁਣ ਰਿਹਾ ਹਾਂ...',
    aiThinking: 'AI ਸੋਚ ਰਿਹਾ ਹੈ...',
    speaking: 'ਬੋਲ ਰਿਹਾ ਹੈ...',
    onboardingTitle: 'ਦਸਤਕਾਰ ਰਜਿਸਟ੍ਰੇਸ਼ਨ (ਸਿਰਫ਼ ਬੋਲ ਕੇ)',
    askNamePrompt: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦੱਸੋ।',
    askVillagePrompt: 'ਬਹੁਤ ਵਧੀਆ! ਤੁਸੀਂ ਕਿਸ ਪਿੰਡ ਜਾਂ ਸ਼ਹਿਰ ਤੋਂ ਹੋ?',
    askCraftPrompt: 'ਤੁਸੀਂ ਕਿਹੜੀ ਰਵਾਇਤੀ ਦਸਤਕਾਰੀ ਜਾਂ ਉਤਪਾਦ ਬਣਾਉਂਦੇ ਹੋ?',
    nameLabel: 'ਦਸਤਕਾਰ ਦਾ ਨਾਮ',
    villageLabel: 'ਪਿੰਡ / ਸ਼ਹਿਰ',
    craftLabel: 'ਦਸਤਕਾਰੀ ਦੀ ਕਿਸਮ',
    createAccountBtn: 'ਖਾਤਾ ਬਣਾਓ ਅਤੇ ਸ਼ੁਰੂ ਕਰੋ',
    accountCreated: 'ਤੁਹਾਡਾ ਖਾਤਾ ਸਫਲਤਾਪੂਰਵਕ ਬਣ ਗਿਆ ਹੈ!',
    sellPageTitle: 'ਨਵਾਂ ਉਤਪਾਦ ਸ਼ਾਮਲ ਕਰੋ (੩ ਆਸਾਨ ਕਦਮ)',
    stepPhotoTitle: 'ਕਦਮ ੧: ਉਤਪਾਦ ਦੀ ਫੋਟੋ ਲਵੋ',
    stepPhotoPrompt: 'ਆਪਣੇ ਉਤਪਾਦ ਦੀ ਇੱਕ ਸਾਫ਼ ਫੋਟੋ ਕੈਮਰੇ ਨਾਲ ਖਿੱਚੋ।',
    stepPhotoAiEnhance: 'AI ਬੈਕਗ੍ਰਾਊਂਡ ਹਟਾ ਕੇ ਸਟੂਡੀਓ ਫੋਟੋ ਬਣਾ ਦੇਵੇਗਾ।',
    takePhotoBtn: 'ਕੈਮਰਾ ਖੋਲ੍ਹੋ',
    uploadPhotoBtn: 'ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
    originalPhoto: 'ਤੁਹਾਡੀ ਖਿੱਚੀ ਹੋਈ ਫੋਟੋ',
    studioPhoto: 'AI ਸਟੂਡੀਓ ਫੋਟੋ',
    stepDescTitle: 'ਕਦਮ ੨: ਉਤਪਾਦ ਬਾਰੇ ਬੋਲ ਕੇ ਦੱਸੋ',
    stepDescPrompt: 'ਇਹ ਤੁਸੀਂ ਕਿਵੇਂ ਬਣਾਇਆ, ਇਸ ਬਾਰੇ ਆਪਣੀ ਬੋਲੀ ਵਿੱਚ ਦੱਸੋ।',
    stepDescExample: '"ਇਹ ਮਿੱਟੀ ਦਾ ਭਾਂਡਾ ਮੈਂ ਹੱਥ ਨਾਲ ਚੱਕ ਉੱਤੇ ਤਿਆਰ ਕੀਤਾ ਹੈ..."',
    stepDescAiEnhance: 'AI ਤੁਹਾਡੇ ਸ਼ਬਦਾਂ ਨੂੰ ਵਧੀਆ ਵਿਕਰੀ ਵੇਰਵੇ ਵਿੱਚ ਬਦਲ ਦੇਵੇਗਾ।',
    stepPriceTitle: 'ਕਦਮ ੩: ਤੁਸੀਂ ਕੀ ਕੀਮਤ ਚਾਹੁੰਦੇ ਹੋ?',
    stepPricePrompt: 'ਦੱਸੋ ਤੁਸੀਂ ਇਸਦੇ ਕਿੰਨੇ ਰੁਪਏ ਲੈਣਾ ਚਾਹੁੰਦੇ ਹੋ।',
    stepPriceMarketCompare: 'AI ਬਾਜ਼ਾਰ ਭਾਅ ਨਾਲ ਤੁਲਨਾ ਕਰਕੇ ਸਹੀ ਕੀਮਤ ਸੁਝਾਏਗਾ।',
    suggestedPriceLabel: 'AI ਸੁਝਾਈ ਗਈ ਬਾਜ਼ਾਰ ਕੀਮਤ',
    yourPriceLabel: 'ਤੁਹਾਡੀ ਕੀਮਤ',
    fairPriceBadge: 'ਵਾਜਬ ਮੁਨਾਫਾ ਗਾਰੰਟੀ',
    reviewTitle: 'ਕਦਮ ੪: ਸਮੀਖਿਆ ਅਤੇ ਪ੍ਰਕਾਸ਼ਨ',
    reviewPrompt: 'ਸਭ ਕੁਝ ਤਿਆਰ ਹੈ! ਕੀ ਬਾਜ਼ਾਰ ਵਿੱਚ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰਨਾ ਹੈ?',
    publishBtn: 'ਵਿਕਰੀ ਲਈ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ',
    publishing: 'ਪ੍ਰਕਾਸ਼ਿਤ ਹੋ ਰਿਹਾ ਹੈ...',
    productPublishedSuccess: 'ਮੁਬਾਰਕਾਂ! ਤੁਹਾਡਾ ਉਤਪਾਦ ਲਾਈਵ ਹੋ ਗਿਆ ਹੈ।',
    viewInStorefront: 'ਖਰੀਦਦਾਰ ਸਟੋਰ ਵਿੱਚ ਦੇਖੋ',
    dashboardTitle: 'ਦਸਤਕਾਰ ਡੈਸ਼ਬੋਰਡ',
    totalSales: 'ਕੁੱਲ ਵਿਕਰੀ ਕਮਾਈ',
    activeOrders: 'ਸਰਗਰਮ ਆਰਡਰ',
    revenueTrends: 'ਆਮਦਨ ਵਿਸ਼ਲੇਸ਼ਣ',
    inventoryControl: 'ਸਟਾਕ ਅਤੇ ਉਤਪਾਦ',
    orderManagement: 'ਆਰਡਰ ਪ੍ਰਬੰਧਨ',
    filterAll: 'ਸਾਰੇ',
    filterPending: 'ਬਾਕੀ',
    filterFulfilled: 'ਪੂਰੇ ਹੋਏ',
    filterCanceled: 'ਰੱਦ ਹੋਏ',
    stockInStock: 'ਉਪਲਬਧ',
    stockLow: 'ਘੱਟ ਸਟਾਕ',
    stockOut: 'ਖਤਮ',
    quickPriceEdit: 'ਕੀਮਤ ਬਦਲੋ',
    saveChanges: 'ਸੰਭਾਲੋ',
    buyerStoreTitle: 'ਭਾਰਤ ਟਿਊਲਿਪ ਬਾਜ਼ਾਰ',
    buyFromArtisan: 'ਸਿੱਧਾ ਪੇਂਡੂ ਦਸਤਕਾਰ ਤੋਂ ਖਰੀਦੋ',
    verifiedArtisan: 'ਪ੍ਰਮਾਣਿਤ ਦਸਤਕਾਰ',
    fairPriceGuarantee: '੧੦੦% ਅਸਲੀ ਦਸਤਕਾਰੀ',
    addToCart: 'ਹੁਣੇ ਖਰੀਦੋ',
    orderPlaced: 'ਆਰਡਰ ਸਫਲਤਾਪੂਰਵਕ ਦਰਜ ਹੋਇਆ!',
    dbInspectorTitle: 'ਸੁਪਾਬੇਸ ਡਾਟਾਬੇਸ ਦ੍ਰਿਸ਼',
    supabaseSynced: 'ਸੁਪਾਬੇਸ ਨਾਲ ਜੁੜਿਆ',
    localStorageFallback: 'ਲੋਕਲ ਡਾਟਾਬੇਸ ਚਾਲੂ ਹੈ',
    tableArtisans: 'ਦਸਤਕਾਰ ਸੂਚੀ',
    tableProducts: 'ਉਤਪਾਦ ਸੂਚੀ',
    tableOrders: 'ਆਰਡਰ ਸੂਚੀ',
    schemaDetails: 'ਡਾਟਾਬੇਸ ਸਕੀਮਾ ਵੇਰਵਾ',
  },
};

export interface StudioUiTranslations {
  companionSubtitle: string;
  assistantBadge: string;
  changeLanguage: string;
  activePromptLabel: string;
  listeningStatus: string;
  speakingStatus: string;
  readyStatus: string;
  listenAgain: string;
  resetConversation: string;
  typeQuestionPlaceholder: string;
  askButton: string;
  listeningTranscript: string;
  categoryPricing: string;
  categorySchemes: string;
  categoryGItag: string;
  categoryPhotography: string;
  categoryPackaging: string;
  categoryPayments: string;
  categoryGeneral: string;
  welcomeSpoken: string;
  welcomeDisplay: string;
  clearChatNotice: string;
}

export const LANGUAGE_CONFIRMATION: Record<SupportedLanguageCode, string> = {
  hi: 'नमस्ते! आपकी भाषा हिन्दी चुन ली गई है। मैं आपकी सहायता के लिए तैयार हूँ। पूछने के लिए माइक दबाएं।',
  ta: 'வணக்கம்! உங்கள் மொழி தமிழ் தேர்ந்தெடுக்கப்பட்டது. உங்களுக்கு உதவ நான் தயாராக உள்ளேன். பேச மைக்கைத் தொடவும்.',
  te: 'నమస్కారం! మీ భాష తెలుగు ఎంపిక చేయబడింది. మీకు సహాయం చేయడానికి నేను సిద్ధంగా ఉన్నాను. మాట్లాడటానికి మైక్ నొక్కండి.',
  bn: 'নমস্কার! আপনার ভাষা বাংলা নির্বাচিত হয়েছে। আমি আপনাকে সাহায্য করতে প্রস্তুত। কথা বলতে মাইকে চাপুন।',
  mr: 'नमस्कार! तुमची भाषा मराठी निवडली गेली आहे. मी तुम्हाला मदत करण्यास तयार आहे. बोलण्यासाठी माइक टॅप करा.',
  gu: 'નમસ્તે! તમારી ભાષા ગુજરાતી પસંદ કરવામાં આવી છે. હું તમને મદદ કરવા તૈયાર છું. બોલવા માટે માઇક દબાવો.',
  kn: 'ನಮಸ್ಕಾರ! ನಿಮ್ಮ ಭಾಷೆ ಕನ್ನಡ ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ. ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ನಾನು ಸಿದ್ಧನಾಗಿದ್ದೇನೆ. ಮಾತನಾಡಲು ಮೈಕ್ ಒತ್ತಿರಿ.',
  ml: 'നമസ്കാരം! നിങ്ങളുടെ ഭാഷ മലയാളം തിരഞ്ഞെടുത്തു. നിങ്ങളെ സഹായിക്കാൻ ഞാൻ തയ്യാറാണ്. സംസാരിക്കാൻ മൈക്ക് അമർത്തുക.',
  or: 'ନମସ୍କାର! ଆପଣଙ୍କ ଭାଷା ଓଡ଼ିଆ ଚୟନ କରାଯାଇଛି। ଆପଣଙ୍କୁ ସାହାଯ୍ୟ କରିବାକୁ ମୁଁ ପ୍ରସ୍ତୁତ। କହିବାକୁ ମାଇକ୍ ଦବାନ୍ତୁ।',
  pa: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਤੁਹਾਡੀ ਬੋਲੀ ਪੰਜਾਬੀ ਚੁਣੀ ਗਈ ਹੈ। ਮੈਂ ਤੁਹਾਡੀ ਮਦਦ ਕਰਨ ਲਈ ਤਿਆਰ ਹਾਂ। ਬੋਲਣ ਲਈ ਮਾਈਕ ਦਬਾਓ।',
  en: 'Welcome! English has been selected. I am your live voice companion. Tap the microphone to talk with me.',
};

export const STUDIO_UI_TRANSLATIONS: Record<SupportedLanguageCode, StudioUiTranslations> = {
  hi: {
    companionSubtitle: 'ग्रामीण और पारंपरिक कारीगरों के लिए एआई आवाज़ साथी',
    assistantBadge: 'लाइव आवाज़ सहायक',
    changeLanguage: 'भाषा बदलें',
    activePromptLabel: 'सक्रिय आवाज़ सलाह',
    listeningStatus: 'सुन रहा हूँ... (अब बोलिए)',
    speakingStatus: 'सलाह बोल रहा हूँ...',
    readyStatus: 'तैयार • बोलने के लिए माइक दबाएं',
    listenAgain: 'फिर से सुनें (आवाज़ चलाएं)',
    resetConversation: 'बातचीत रीसेट करें',
    typeQuestionPlaceholder: 'या सवाल टाइप करें (उचित मूल्य, विश्वकर्मा योजना, फोटोग्राफी)...',
    askButton: 'पूछें',
    listeningTranscript: 'आपकी आवाज़ सुनी जा रही है... माइक में साफ़ बोलें',
    categoryPricing: '💰 उचित मूल्य निर्धारण',
    categorySchemes: '🏛️ पीएम विश्वकर्मा योजना',
    categoryGItag: '🏷️ जीआई टैग प्रमाणन',
    categoryPhotography: '📸 उत्पाद फोटोग्राफी',
    categoryPackaging: '📦 सुरक्षित पैकेजिंग',
    categoryPayments: '💳 डिजिटल भुगतान व बैंक',
    categoryGeneral: '🌸 कारीगर मार्गदर्शिका',
    welcomeSpoken: 'नमस्ते! मैं आपकी भारत ट्यूलिप लाइव आवाज़ सहायक हूँ। हस्तशिल्प का उचित मूल्य तय करने, पीएम विश्वकर्मा योजना का लाभ लेने या उत्पाद फोटोग्राफी के बारे में मुझसे पूछने के लिए माइक दबाएं।',
    welcomeDisplay: '**भारत ट्यूलिप कारीगर आवाज़ स्टूडियो में आपका स्वागत है** 🌸\n\nमैं आपकी समर्पित लाइव आवाज़ सहायक हूँ। मैं आपकी सहायता कर सकती हूँ:\n- **उचित मूल्य निर्धारण:** कच्चा माल, श्रम और 30% लाभ की गणना\n- **पीएम विश्वकर्मा योजना:** ₹15,000 टूलकिट अनुदान और 5% ब्याज पर ऋण\n- **जीआई टैग प्रमाणन:** पारंपरिक शिल्प की प्रामाणिकता और सुरक्षा\n- **उत्पाद फोटोग्राफी:** प्राकृतिक रोशनी में आकर्षक तस्वीरें खींचना\n\nमाइक दबाकर बोलें या नीचे अपना प्रश्न लिखें!',
    clearChatNotice: 'बातचीत रीसेट हो गई। नया सवाल पूछने के लिए माइक दबाएं या नीचे लिखें।',
  },
  ta: {
    companionSubtitle: 'கிராமப்புற மற்றும் பாரம்பரிய கைவினைஞர்களுக்கான AI குரல் துணைவர்',
    assistantBadge: 'நேரடி குரல் உதவியாளர்',
    changeLanguage: 'மொழியை மாற்றவும்',
    activePromptLabel: 'செயலில் உள்ள குரல் வழிகாட்டல்',
    listeningStatus: 'கேட்கிறது... (இப்போது பேசுங்கள்)',
    speakingStatus: 'வழிகாட்டல் பேசுகிறது...',
    readyStatus: 'தயார் • பேச மைக்கை அழுத்தவும்',
    listenAgain: 'மீண்டும் கேளுங்கள் (ஒலி இயக்கவும்)',
    resetConversation: 'உரையாடலை மீட்டமைக்கவும்',
    typeQuestionPlaceholder: 'அல்லது கேள்வியைத் தட்டச்சு செய்யவும் (விலை, விஸ்வகர்மா திட்டம், புகைப்படம்)...',
    askButton: 'கேளுங்கள்',
    listeningTranscript: 'உங்கள் குரல் கேட்கப்படுகிறது... மைக்கில் தெளிவாகப் பேசுங்கள்',
    categoryPricing: '💰 நியாயமான விலை நிர்ணயம்',
    categorySchemes: '🏛️ பிஎம் விஸ்வகர்மா திட்டம்',
    categoryGItag: '🏷️ ஜிஐ (GI) புவிசார் குறியீடு',
    categoryPhotography: '📸 தயாரிப்பு புகைப்படம்',
    categoryPackaging: '📦 பாதுகாப்பான பேக்கேஜிங்',
    categoryPayments: '💳 டிஜிட்டல் கொடுப்பனவுகள்',
    categoryGeneral: '🌸 கைவினைஞர் வழிகாட்டி',
    welcomeSpoken: 'வணக்கம்! நான் உங்கள் பாரத் துலிப் நேரடி குரல் உதவியாளர். கைவினைப் பொருட்களின் நியாயமான விலை, பிஎம் விஸ்வகர்மா திட்டம் அல்லது தயாரிப்பு புகைப்படம் பற்றி என்னிடம் பேச மைக்கைத் தொடவும்.',
    welcomeDisplay: '**பாரத் துலிப் கைவினைஞர் குரல் ஸ்டுடியோவிற்கு வரவேற்கிறோம்** 🌸\n\nநான் உங்கள் நேரடி குரல் உதவியாளர். நான் உங்களுக்கு உதவ முடியும்:\n- **நியாயமான விலை:** மூலப்பொருட்கள், கைவினை ஊதியம் மற்றும் 30% லாபக் கணக்கீடு\n- **பிஎம் விஸ்வகர்மா திட்டம்:** ₹15,000 கருவித்தொகுப்பு மானியம் & 5% வட்டி கடன்\n- **ஜிஐ குறியீடு:** பாரம்பரிய கலையின் உண்மைத்தன்மை மற்றும் பாதுகாப்பு\n- **தயாரிப்பு புகைப்படம்:** இயற்கை ஒளியில் கவர்ச்சிகரமான படங்கள்\n\nபேச மைக்கைத் தொடவும் அல்லது கீழே உங்கள் கேள்வியை எழுதவும்!',
    clearChatNotice: 'உரையாடல் அழிக்கப்பட்டது. பேச மைக்கைத் தொடவும் அல்லது கீழே தட்டச்சு செய்யவும்.',
  },
  te: {
    companionSubtitle: 'గ్రామీణ మరియు సాంప్రదాయ కళాకారుల కోసం AI వాయిస్ సహచరుడు',
    assistantBadge: 'లైవ్ వాయిస్ అసిస్టెంట్',
    changeLanguage: 'భాష మార్చండి',
    activePromptLabel: 'క్రియాశీల వాయిస్ సలహా',
    listeningStatus: 'వింటోంది... (ఇప్పుడు మాట్లాడండి)',
    speakingStatus: 'సలహా మాట్లాడుతోంది...',
    readyStatus: 'సిద్ధంగా ఉంది • మాట్లాడటానికి మైక్ నొక్కండి',
    listenAgain: 'మళ్ళీ వినండి (ఆడియో ప్లే)',
    resetConversation: 'సంభాషణను రీసెట్ చేయండి',
    typeQuestionPlaceholder: 'లేదా ప్రశ్న టైప్ చేయండి (ధర, విశ్వకర్మ పథకం, ఫోటోగ్రఫీ)...',
    askButton: 'అడగండి',
    listeningTranscript: 'మీ వాయిస్ వినబడుతోంది... మైక్‌లో స్పష్టంగా మాట్లాడండి',
    categoryPricing: '💰 సరసమైన ధర నిర్ణయం',
    categorySchemes: '🏛️ పీఎం విశ్వకర్మ పథకం',
    categoryGItag: '🏷️ జీఐ (GI) ట్యాగ్ సర్టిఫికేషన్',
    categoryPhotography: '📸 క్రాఫ్ట్ ఫోటోగ్రఫీ',
    categoryPackaging: '📦 సురక్షిత ప్యాకేజింగ్',
    categoryPayments: '💳 డిజిటల్ చెల్లింపులు',
    categoryGeneral: '🌸 కళాకారుల గైడ్',
    welcomeSpoken: 'నమస్కారం! నేను మీ భారత్ ట్యులిప్ లైవ్ వాయిస్ అసిస్టెంట్‌ని. సరసమైన ధరలు, పీఎం విశ్వకర్మ పథకం లేదా ఫోటోగ్రఫీ గురించి నాతో మాట్లాడటానికి మైక్ నొక్కండి.',
    welcomeDisplay: '**భారత్ ట్యులిప్ కళాకారుల వాయిస్ స్టూడియోకి స్వాగతం** 🌸\n\nనేను మీ లైవ్ వాయిస్ గైడ్:\n- **సరసమైన ధర:** ముడిసరుకు, కార్మిక కూలీ & 30% లాభం లెక్కింపు\n- **పీఎం విశ్వకర్మ పథకం:** ₹15,000 టూల్‌కిట్ గ్రాంట్ & 5% వడ్డీ రుణాలు\n- **జీఐ ట్యాగ్:** సాంప్రదాయ హస్తకళల గుర్తింపు మరియు రక్షణ\n- **ఫోటోగ్రఫీ:** సహజ కాంతిలో అద్భుతమైన ఉత్పత్తి ఫోటోలు\n\nమాట్లాడటానికి మైక్ నొక్కండి లేదా మీ ప్రశ్న రాయండి!',
    clearChatNotice: 'చాట్ క్లియర్ చేయబడింది. మాట్లాడటానికి మైక్ నొక్కండి లేదా టైప్ చేయండి.',
  },
  bn: {
    companionSubtitle: 'গ্রামীণ ও ঐতিহ্যবাহী কারিগরদের জন্য এআই ভয়েস সহকারী',
    assistantBadge: 'লাইভ ভয়েস সহকারী',
    changeLanguage: 'ভাষা পরিবর্তন',
    activePromptLabel: 'সক্রিয় ভয়েস পরামর্শ',
    listeningStatus: 'শুনছি... (এখন কথা বলুন)',
    speakingStatus: 'পরামর্শ বলা হচ্ছে...',
    readyStatus: 'প্রস্তুত • কথা বলতে মাইক স্পর্শ করুন',
    listenAgain: 'আবার শুনুন (অডিও বাজান)',
    resetConversation: 'কথোপকথন রিসেট করুন',
    typeQuestionPlaceholder: 'অথবা প্রশ্ন লিখুন (দাম, বিশ্বকর্মা প্রকল্প, ফটোগ্রাফি)...',
    askButton: 'জিজ্ঞাসা করুন',
    listeningTranscript: 'আপনার কথা শোনা হচ্ছে... মাইকে স্পষ্টভাবে বলুন',
    categoryPricing: '💰 ন্যায্য মূল্য নির্ধারণ',
    categorySchemes: '🏛️ পিএম বিশ্বকর্মা যোজনা',
    categoryGItag: '🏷️ জিআই (GI) ট্যাগ শংসাপত্র',
    categoryPhotography: '📸 কারুকাজ ফটোগ্রাফি',
    categoryPackaging: '📦 নিরাপদ প্যাকেজিং',
    categoryPayments: '💳 ডিজিটাল পেমেন্ট',
    categoryGeneral: '🌸 কারিগর গাইড',
    welcomeSpoken: 'নমস্কার! আমি আপনার ভারত টিউলিপ লাইভ ভয়েস সহকারী। হস্তশিল্পের সঠিক দাম, পিএম বিশ্বকর্মা যোজনা বা ফটোগ্রাফি সম্পর্কে জানতে মাইকে ট্যাপ করুন।',
    welcomeDisplay: '**ভারত টিউলিপ কারিগর ভয়েস স্টুডিওতে স্বাগতম** 🌸\n\nআমি আপনার লাইভ ভয়েস সঙ্গী:\n- **ন্যায্য মূল্য নির্ধারণ:** কাঁচামাল, পারিশ্রমিক ও ৩০% লাভের হিসাব\n- **পিএম বিশ্বকর্মা যোজনা:** ₹১৫,০০০ টুলকিট অনুদান ও ৫% সুদে ঋণ\n- **জিআই ট্যাগ:** ঐতিহ্যবাহী শিল্পের সুরক্ষা ও উচ্চ মূল্য\n- **ফটোগ্রাফি:** প্রাকৃতিক আলোয় সুন্দর ছবি তোলার কৌশল\n\nকথা বলতে মাইকে চাপুন অথবা নিচে প্রশ্ন লিখুন!',
    clearChatNotice: 'কথোপকথন রিসেট হয়েছে। কথা বলতে মাইকে চাপুন বা নিচে লিখুন।',
  },
  mr: {
    companionSubtitle: 'ग्रामीण व पारंपरिक कारागिरांसाठी एआय व्हॉईस साथी',
    assistantBadge: 'थेट व्हॉईस सहाय्यक',
    changeLanguage: 'भाषा बदला',
    activePromptLabel: 'सक्रिय व्हॉईस मार्गदर्शन',
    listeningStatus: 'ऐकत आहे... (आता बोला)',
    speakingStatus: 'सल्ला सांगत आहे...',
    readyStatus: 'सज्ज • बोलण्यासाठी माइक दाबा',
    listenAgain: 'पुन्हा ऐका (ऑडिओ प्ले)',
    resetConversation: 'संभाषण रीसेट करा',
    typeQuestionPlaceholder: 'किंवा प्रश्न टाईप करा (किंमत, विश्वकर्मा योजना, फोटो)...',
    askButton: 'विचारा',
    listeningTranscript: 'तुमचा आवाज ऐकला जात आहे... माइकमध्ये स्पष्ट बोला',
    categoryPricing: '💰 योग्य किंमत निर्धारण',
    categorySchemes: '🏛️ पीएम विश्वकर्मा योजना',
    categoryGItag: '🏷️ जीआय (GI) टॅग प्रमाणपत्र',
    categoryPhotography: '📸 हस्तकला छायाचित्रण',
    categoryPackaging: '📦 सुरक्षित पॅकेजिंग',
    categoryPayments: '💳 डिजिटल पेमेंट आणि बँक',
    categoryGeneral: '🌸 कारागीर मार्गदर्शक',
    welcomeSpoken: 'नमस्कार! मी तुमची भारत ट्यूलिप थेट व्हॉईस सहाय्यक आहे. हस्तकलेचे योग्य मूल्य, पीएम विश्वकर्मा योजना किंवा छायाचित्रणाबद्दल विचारण्यासाठी माइक टॅप करा.',
    welcomeDisplay: '**भारत ट्यूलिप कारागीर व्हॉईस स्टुडिओमध्ये आपले स्वागत आहे** 🌸\n\nमी तुमची थेट व्हॉईस मार्गदर्शक आहे:\n- **योग्य किंमत:** कच्चा माल, श्रम आणि ३०% नफ्याची अचूक गणना\n- **पीएम विश्वकर्मा योजना:** ₹१५,००० टूलकिट अनुदान आणि ५% सवलतीचे कर्ज\n- **जीआय टॅग:** प्रामाणिक हस्तकलेचे कायदेशीर संरक्षण\n- **उत्पादन फोटोग्राफी:** नैसर्गिक प्रकाशात आकर्षक फोटो काढणे\n\nबोलण्यासाठी माइक दाबा किंवा खाली प्रश्न लिहा!',
    clearChatNotice: 'संभाषण रीसेट झाले. बोलण्यासाठी माइक दाबा किंवा टाईप करा.',
  },
  gu: {
    companionSubtitle: 'ગ્રામીણ અને પરંપરાગત કારીગરો માટે એઆઈ વૉઇસ સહાયક',
    assistantBadge: 'લાઇવ વૉઇસ સહાયક',
    changeLanguage: 'ભાષા બદલો',
    activePromptLabel: 'સક્રિય વૉઇસ સલાહ',
    listeningStatus: 'સાંભળી રહ્યો છું... (હવે બોલો)',
    speakingStatus: 'સલાહ બોલી રહ્યો છું...',
    readyStatus: 'તૈયાર • બોલવા માટે માઇક દબાવો',
    listenAgain: 'ફરીથી સાંભળો (ઑડિયો ચલાવો)',
    resetConversation: 'વાતચીત રીસેટ કરો',
    typeQuestionPlaceholder: 'અથવા પ્રશ્ન લખો (વાજબી કિંમત, વિશ્વકર્મા યોજના, ફોટો)...',
    askButton: 'પૂછો',
    listeningTranscript: 'તમારો અવાજ સંભળાઈ રહ્યો છે... માઇકમાં સ્પષ્ટ બોલો',
    categoryPricing: '💰 વાજબી કિંમત નિર્ધારણ',
    categorySchemes: '🏛️ પીએમ વિશ્વકર્મા યોજના',
    categoryGItag: '🏷️ જીઆઈ (GI) ટૅગ પ્રમાણપત્ર',
    categoryPhotography: '📸 પ્રોડક્ટ ફોટોગ્રાફી',
    categoryPackaging: '📦 સુરક્ષિત પેકેજિંગ',
    categoryPayments: '💳 ડિજિટલ ચૂકવણી',
    categoryGeneral: '🌸 કારીગર માર્ગદર્શક',
    welcomeSpoken: 'નમસ્તે! હું તમારી ભારત ટ્યૂલિપ લાઇવ વૉઇસ સહાયક છું. હસ્તકલાની યોગ્ય કિંમત, પીએમ વિશ્વકર્મા યોજના અથવા ફોટોગ્રાફી વિશે પૂછવા માટે માઇક દબાવો.',
    welcomeDisplay: '**ભારત ટ્યૂલિપ કારીગર વૉઇસ સ્ટુડિયોમાં આપનું સ્વાગત છે** 🌸\n\nહું તમારી લાઇવ વૉઇસ સહાયક છું:\n- **વાજબી કિંમત:** કાચો માલ, મજૂરી અને ૩૦% નફાની ગણતરી\n- **પીએમ વિશ્વકર્મા યોજના:** ₹૧૫,૦૦૦ ટૂલકીટ ગ્રાન્ટ અને ૫% વ્યાજે લોન\n- **જીઆઈ ટૅગ:** પરંપરાગત કલાનું પ્રમાણપત્ર અને સુરક્ષા\n- **ફોટોગ્રાફી:** કુદરતી પ્રકાશમાં આકર્ષક તસવીરો લેવી\n\nબોલવા માટે માઇક દબાવો અથવા નીચે પ્રશ્ન લખો!',
    clearChatNotice: 'ચેટ સાફ થઈ ગઈ. બોલવા માટે માઇક દબાવો અથવા લખો.',
  },
  kn: {
    companionSubtitle: 'ಗ್ರಾಮೀಣ ಮತ್ತು ಸಾಂಪ್ರದಾಯಿಕ ಕುಶಲಕರ್ಮಿಗಳಿಗೆ AI ಧ್ವನಿ ಸಹಾಯಕ',
    assistantBadge: 'ಲೈವ್ ವಾಯ್ಸ್ ಸಹಾಯಕ',
    changeLanguage: 'ಭಾಷೆ ಬದಲಾಯಿಸಿ',
    activePromptLabel: 'ಸಕ್ರಿಯ ಧ್ವನಿ ಸಲಹೆ',
    listeningStatus: 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದೇನೆ... (ಈಗ ಮಾತನಾಡಿ)',
    speakingStatus: 'ಸಲಹೆ ನೀಡುತ್ತಿದ್ದೇನೆ...',
    readyStatus: 'ಸಿದ್ಧವಾಗಿದೆ • ಮಾತನಾಡಲು ಮೈಕ್ ಒತ್ತಿರಿ',
    listenAgain: 'ಮತ್ತೆ ಆಲಿಸಿ (ಆಡಿಯೊ ಪ್ಲೇ)',
    resetConversation: 'ಸಂಭಾಷಣೆ ಮರುಹೊಂದಿಸಿ',
    typeQuestionPlaceholder: 'ಅಥವಾ ಪ್ರಶ್ನೆ ಟೈಪ್ ಮಾಡಿ (ಬೆಲೆ, ವಿಶ್ವಕರ್ಮ ಯೋಜನೆ, ಫೋಟೋ)...',
    askButton: 'ಕೇಳಿ',
    listeningTranscript: 'ನಿಮ್ಮ ಧ್ವನಿ ಕೇಳಿಸುತ್ತಿದೆ... ಮೈಕ್‌ನಲ್ಲಿ ಸ್ಪಷ್ಟವಾಗಿ ಮಾತನಾಡಿ',
    categoryPricing: '💰 ನ್ಯಾಯಯುತ ಬೆಲೆ ನಿರ್ಧಾರ',
    categorySchemes: '🏛️ ಪಿಎಂ ವಿಶ್ವಕರ್ಮ ಯೋಜನೆ',
    categoryGItag: '🏷️ ಜಿಐ (GI) ಟ್ಯಾಗ್ ಪ್ರಮಾಣೀಕರಣ',
    categoryPhotography: '📸 ಕರಕುಶಲ ಛಾಯಾಗ್ರಹಣ',
    categoryPackaging: '📦 ಸುರಕ್ಷಿತ ಪ್ಯಾಕೇಜಿಂಗ್',
    categoryPayments: '💳 ಡಿಜಿಟಲ್ ಪಾವತಿಗಳು',
    categoryGeneral: '🌸 ಕುಶಲಕರ್ಮಿ ಮಾರ್ಗದರ್ಶಿ',
    welcomeSpoken: 'ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ ಭಾರತ ಟುಲಿಪ್ ಲೈವ್ ವಾಯ್ಸ್ ಸಹಾಯಕ. ನಿಮ್ಮ ಕರಕುಶಲ ವಸ್ತುಗಳ ನ್ಯಾಯಯುತ ಬೆಲೆ, ಪಿಎಂ ವಿಶ್ವಕರ್ಮ ಯೋಜನೆ ಅಥವಾ ಛಾಯಾಗ್ರಹಣದ ಬಗ್ಗೆ ಕೇಳಲು ಮೈಕ್ ಒತ್ತಿರಿ.',
    welcomeDisplay: '**ಭಾರತ ಟುಲಿಪ್ ಕುಶಲಕರ್ಮಿ ವಾಯ್ಸ್ ಸ್ಟುಡಿಯೋಗೆ ಸುಸ್ವಾಗತ** 🌸\n\nನಾನು ನಿಮ್ಮ ಲೈವ್ ವಾಯ್ಸ್ ಗೈಡ್:\n- **ನ್ಯಾಯಯುತ ಬೆಲೆ:** ಕಚ್ಚಾ ವಸ್ತುಗಳು, ಕಾರ್ಮಿಕ ಕೂಲಿ ಮತ್ತು ೩೦% ಲಾಭದ ಲೆಕ್ಕಾಚಾರ\n- **ಪಿಎಂ ವಿಶ್ವಕರ್ಮ ಯೋಜನೆ:** ₹೧೫,೦೦೦ ಟೂಲ್‌ಕಿಟ್ ಅನುದಾನ & ೫% ಬಡ್ಡಿ ಸಾಲ\n- **ಜಿಐ ಟ್ಯಾಗ್:** ಸಾಂಪ್ರದಾಯಿಕ ಕಲೆಯ ದೃಢೀಕರಣ ಮತ್ತು ರಕ್ಷಣೆ\n- **ಫೋಟೋಗ್ರಫಿ:** ನೈಸರ್ಗಿಕ ಬೆಳಕಿನಲ್ಲಿ ಅದ್ಭುತ ಉತ್ಪನ್ನ ಫೋಟೋಗಳು\n\nಮಾತನಾಡಲು ಮೈಕ್ ಒತ್ತಿರಿ ಅಥವಾ ಕೆಳಗೆ ಬರೆಯಿರಿ!',
    clearChatNotice: 'ಸಂಭಾಷಣೆ ತೆರವುಗೊಳಿಸಲಾಗಿದೆ. ಮಾತನಾಡಲು ಮೈಕ್ ಒತ್ತಿರಿ.',
  },
  ml: {
    companionSubtitle: 'ഗ്രാമീണ, പാരമ്പര്യ കരകൗശല വിദഗ്ദ്ധർക്കുള്ള AI ശബ്ദ സഹായി',
    assistantBadge: 'ലൈവ് വോയ്സ് സഹായി',
    changeLanguage: 'ഭാഷ മാറ്റുക',
    activePromptLabel: 'സജീവ ശബ്ദ ഉപദേശം',
    listeningStatus: 'കേൾക്കുന്നു... (ഇപ്പോൾ സംസാരിക്കുക)',
    speakingStatus: 'ഉപദേശം പറയുന്നു...',
    readyStatus: 'തയ്യാറാണ് • സംസാരിക്കാൻ മൈക്ക് അമർത്തുക',
    listenAgain: 'വീണ്ടും കേൾക്കുക (ഓഡിയോ)',
    resetConversation: 'സംഭാഷണം പുനഃക്രമീകരിക്കുക',
    typeQuestionPlaceholder: 'അല്ലെങ്കിൽ ചോദ്യം എഴുതുക (വില, വിശ്വകർമ പദ്ധതി, ഫോട്ടോ)...',
    askButton: 'ചോദിക്കുക',
    listeningTranscript: 'നിങ്ങളുടെ ശബ്ദം കേൾക്കുന്നു... മൈക്കിൽ വ്യക്തമായി സംസാരിക്കുക',
    categoryPricing: '💰 ന്യായമായ വില നിർണ്ണയം',
    categorySchemes: '🏛️ പിഎം വിശ്വകർമ പദ്ധതി',
    categoryGItag: '🏷️ ജിഐ (GI) ടാഗ് സർട്ടിഫിക്കേഷൻ',
    categoryPhotography: '📸 ക്രാഫ്റ്റ് ഫോട്ടോഗ്രാഫി',
    categoryPackaging: '📦 സുരക്ഷിത പാക്കേജിംഗ്',
    categoryPayments: '💳 ഡിജിറ്റൽ പേയ്‌മെന്റുകൾ',
    categoryGeneral: '🌸 കരകൗശല സഹായി',
    welcomeSpoken: 'നമസ്കാരം! ഞാൻ നിങ്ങളുടെ ഭാരത് ട്യൂലിപ് ലൈവ് വോയ്സ് സഹായി. ന്യായമായ വില, പിഎം വിശ്വകർമ പദ്ധതി അല്ലെങ്കിൽ ഫോട്ടോഗ്രാഫി എന്നിവയെക്കുറിച്ച് സംസാരിക്കാൻ മൈക്ക് അമർത്തുക.',
    welcomeDisplay: '**ഭാരത് ട്യൂലിപ് കരകൗശല വോയ്സ് സ്റ്റുഡിയോയിലേക്ക് സ്വാഗതം** 🌸\n\nഞാൻ നിങ്ങളുടെ ലൈവ് വോയ്സ് ഗൈഡ്:\n- **ന്യായമായ വില:** അസംസ്കൃത വസ്തുക്കൾ, കൂലി, 30% ലാഭം കണക്കുകൂട്ടൽ\n- **പിഎം വിശ്വകർമ പദ്ധതി:** ₹15,000 ടൂൾകിറ്റ് ഗ്രാന്റ് & 5% പലിശ വായ്പ\n- **ജിഐ ടാഗ്:** പാരമ്പര്യ കലയുടെ ആധികാരികതയും സംരക്ഷണവും\n- **ഫോട്ടോഗ്രാഫി:** പ്രകൃതിദത്ത വെളിച്ചത്തിൽ മികച്ച ചിത്രങ്ങൾ\n\nസംസാരിക്കാൻ മൈക്ക് അമർത്തുക അല്ലെങ്കിൽ താഴെ എഴുതുക!',
    clearChatNotice: 'ചാറ്റ് മായ്‌ച്ചു. സംസാരിക്കാൻ മൈക്ക് അമർത്തുക.',
  },
  or: {
    companionSubtitle: 'ଗ୍ରାମୀଣ ଓ ପାରମ୍ପରିକ ଶିଳ୍ପୀମାନଙ୍କ ପାଇଁ ଏଆଇ ଭଏସ୍ ସହାୟକ',
    assistantBadge: 'ଲାଇଭ୍ ଭଏସ୍ ସହାୟକ',
    changeLanguage: 'ଭାଷା ବଦଳାନ୍ତୁ',
    activePromptLabel: 'ସକ୍ରିୟ ଭଏସ୍ ପରାମର୍ଶ',
    listeningStatus: 'ଶୁଣୁଛି... (ଏବେ କୁହନ୍ତୁ)',
    speakingStatus: 'ପରାମର୍ଶ କହୁଛି...',
    readyStatus: 'ପ୍ରସ୍ତୁତ • କହିବାକୁ ମାଇକ୍ ଦବାନ୍ତୁ',
    listenAgain: 'ପୁଣି ଶୁଣନ୍ତୁ (ଅଡିଓ)',
    resetConversation: 'କଥାବାର୍ତ୍ତା ରିସେଟ୍ କରନ୍ତୁ',
    typeQuestionPlaceholder: 'କିମ୍ବା ପ୍ରଶ୍ନ ଲେଖନ୍ତୁ (ମୂଲ୍ୟ, ବିଶ୍ୱକର୍ମା ଯୋଜନା, ଫଟୋ)...',
    askButton: 'ପଚାରନ୍ତୁ',
    listeningTranscript: 'ଆପଣଙ୍କ ସ୍ୱର ଶୁଣାଯାଉଛି... ମାଇକରେ ସ୍ପଷ୍ଟ କୁହନ୍ତୁ',
    categoryPricing: '💰 ଉଚିତ୍ ମୂଲ୍ୟ ନିର୍ଦ୍ଧାରଣ',
    categorySchemes: '🏛️ ପିଏମ୍ ବିଶ୍ୱକର୍ମା ଯୋଜନା',
    categoryGItag: '🏷️ ଜିଆଇ (GI) ଟ୍ୟାଗ୍ ପ୍ରମାଣପତ୍ର',
    categoryPhotography: '📸 ଶିଳ୍ପ ଫଟୋଗ୍ରାଫି',
    categoryPackaging: '📦 ସୁରକ୍ଷିତ ପ୍ୟାକେଜିଂ',
    categoryPayments: '💳 ଡିଜିଟାଲ୍ ପେମେଣ୍ଟ',
    categoryGeneral: '🌸 ଶିଳ୍ପୀ ମାର୍ଗଦର୍ଶିକା',
    welcomeSpoken: 'ନମସ୍କାର! ମୁଁ ଆପଣଙ୍କ ଭାରତ ଟିଉଲିପ୍ ଲାଇଭ୍ ଭଏସ୍ ସହାୟକ। ଆପଣଙ୍କ ହସ୍ତଶିଳ୍ପର ଉଚିତ୍ ମୂଲ୍ୟ, ପିଏମ୍ ବିଶ୍ୱକର୍ମା ଯୋଜନା ବା ଫଟୋଗ୍ରାଫି ବିଷୟରେ ପଚାରିବାକୁ ମାଇକ୍ ଦବାନ୍ତୁ।',
    welcomeDisplay: '**ଭାରତ ଟିଉଲିପ୍ ଶିଳ୍ପୀ ଭଏସ୍ ଷ୍ଟୁଡିଓକୁ ସ୍ୱାଗତ** 🌸\n\nମୁଁ ଆପଣଙ୍କ ଲାଇଭ୍ ଭଏସ୍ ସହାୟକ:\n- **ଉଚିତ୍ ମୂଲ୍ୟ ନିର୍ଦ୍ଧାରଣ:** କଞ୍ଚାମାଲ, ମଜୁରୀ ଓ ୩୦% ଲାଭର ଗଣନା\n- **ପିଏମ୍ ବିଶ୍ୱକର୍ମା ଯୋଜନା:** ₹୧୫,୦୦୦ ଟୁଲକିଟ୍ ଅନୁଦାନ ଓ ୫% ସୁଧରେ ଋଣ\n- **ଜିଆଇ ଟ୍ୟାଗ୍:** ପାରମ୍ପରିକ କଳାର ସୁରକ୍ଷା ଓ ଅଧିକ ମୂଲ୍ୟ\n- **ଫଟୋଗ୍ରାଫି:** ପ୍ରାକୃତିକ ଆଲୋକରେ ସୁନ୍ଦର ଫଟୋ ଉଠାଇବା କୌଶଳ\n\nକହିବାକୁ ମାଇକ୍ ଦବାନ୍ତୁ କିମ୍ବା ତଳେ ପ୍ରଶ୍ନ ଲେଖନ୍ତୁ!',
    clearChatNotice: 'କଥାବାର୍ତ୍ତା ରିସେଟ୍ ହୋଇଛି। କହିବାକୁ ମାଇକ୍ ଦବାନ୍ତୁ।',
  },
  pa: {
    companionSubtitle: 'ਪੇਂਡੂ ਅਤੇ ਰਵਾਇਤੀ ਦਸਤਕਾਰਾਂ ਲਈ ਏਆਈ ਵਾਇਸ ਸਾਥੀ',
    assistantBadge: 'ਲਾਈਵ ਵਾਇਸ ਸਹਾਇਕ',
    changeLanguage: 'ਬੋਲੀ ਬਦਲੋ',
    activePromptLabel: 'ਸਰਗਰਮ ਵਾਇਸ ਸਲਾਹ',
    listeningStatus: 'ਸੁਣ ਰਿਹਾ ਹਾਂ... (ਹੁਣ ਬੋਲੋ)',
    speakingStatus: 'ਸਲਾਹ ਬੋਲ ਰਿਹਾ ਹਾਂ...',
    readyStatus: 'ਤਿਆਰ • ਬੋਲਣ ਲਈ ਮਾਈਕ ਦਬਾਓ',
    listenAgain: 'ਦੁਬਾਰਾ ਸੁਣੋ (ਆਡੀਓ ਚਲਾਓ)',
    resetConversation: 'ਗੱਲਬਾਤ ਰੀਸੈੱਟ ਕਰੋ',
    typeQuestionPlaceholder: 'ਜਾਂ ਸਵਾਲ ਲਿਖੋ (ਕੀਮਤ, ਵਿਸ਼ਵਕਰਮਾ ਯੋਜਨਾ, ਫੋਟੋ)...',
    askButton: 'ਪੁੱਛੋ',
    listeningTranscript: 'ਤੁਹਾਡੀ ਆਵਾਜ਼ ਸੁਣੀ ਜਾ ਰਹੀ ਹੈ... ਮਾਈਕ ਵਿੱਚ ਸਾਫ਼ ਬੋਲੋ',
    categoryPricing: '💰 ਵਾਜਬ ਕੀਮਤ ਨਿਰਧਾਰਨ',
    categorySchemes: '🏛️ ਪੀਐਮ ਵਿਸ਼ਵਕਰਮਾ ਯੋਜਨਾ',
    categoryGItag: '🏷️ ਜੀਆਈ (GI) ਟੈਗ ਸਰਟੀਫਿਕੇਟ',
    categoryPhotography: '📸 ਸ਼ਿਲਪਕਾਰੀ ਫੋਟੋਗ੍ਰਾਫੀ',
    categoryPackaging: '📦 ਸੁਰੱਖਿਅਤ ਪੈਕਿੰਗ',
    categoryPayments: '💳 ਡਿਜੀਟਲ ਭੁਗਤਾਨ',
    categoryGeneral: '🌸 ਦਸਤਕਾਰ ਗਾਈਡ',
    welcomeSpoken: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਤੁਹਾਡੀ ਭਾਰਤ ਟਿਊਲਿਪ ਲਾਈਵ ਵਾਇਸ ਸਹਾਇਕ ਹਾਂ। ਦਸਤਕਾਰੀ ਦੀ ਸਹੀ ਕੀਮਤ, ਪੀਐਮ ਵਿਸ਼ਵਕਰਮਾ ਯੋਜਨਾ ਜਾਂ ਫੋਟੋਗ੍ਰਾਫੀ ਬਾਰੇ ਪੁੱਛਣ ਲਈ ਮਾਈਕ ਦਬਾਓ।',
    welcomeDisplay: '**ਭਾਰਤ ਟਿਊਲਿਪ ਦਸਤਕਾਰ ਵਾਇਸ ਸਟੂਡੀਓ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ** 🌸\n\nਮੈਂ ਤੁਹਾਡੀ ਲਾਈਵ ਵਾਇਸ ਸਾਥੀ ਹਾਂ:\n- **ਵਾਜਬ ਕੀਮਤ:** ਕੱਚਾ ਮਾਲ, ਮਜ਼ਦੂਰੀ ਅਤੇ 30% ਮੁਨਾਫ਼ੇ ਦੀ ਸਹੀ ਗਣਨਾ\n- **ਪੀਐਮ ਵਿਸ਼ਵਕਰਮਾ ਯੋਜਨਾ:** ₹15,000 ਟੂਲਕਿੱਟ ਗ੍ਰਾਂਟ ਅਤੇ 5% ਵਿਆਜ ਤੇ ਕਰਜ਼ਾ\n- **ਜੀਆਈ ਟੈਗ:** ਰਵਾਇਤੀ ਕਲਾ ਦੀ ਪਛਾਣ ਅਤੇ ਸੁਰੱਖਿਆ\n- **ਫੋਟੋਗ੍ਰਾਫੀ:** ਕੁਦਰਤੀ ਰੌਸ਼ਨੀ ਵਿੱਚ ਵਧੀਆ ਫੋਟੋਆਂ ਖਿੱਚਣਾ\n\nਬੋਲਣ ਲਈ ਮਾਈਕ ਦਬਾਓ ਜਾਂ ਹੇਠਾਂ ਆਪਣਾ ਸਵਾਲ ਲਿਖੋ!',
    clearChatNotice: 'ਗੱਲਬਾਤ ਰੀਸੈੱਟ ਹੋ ਗਈ ਹੈ। ਬੋਲਣ ਲਈ ਮਾਈਕ ਦਬਾਓ।',
  },
  en: {
    companionSubtitle: 'AI Voice Companion for Rural & Traditional Artisans',
    assistantBadge: 'Live Voice Assistant',
    changeLanguage: 'Change Language',
    activePromptLabel: 'Active Voice Advice',
    listeningStatus: 'Listening... (Speak now)',
    speakingStatus: 'Speaking advice...',
    readyStatus: 'Ready • Tap Mic to Speak',
    listenAgain: 'Listen Again (Play Audio)',
    resetConversation: 'Reset Conversation',
    typeQuestionPlaceholder: 'Or type a question (pricing, Vishwakarma scheme, photography)...',
    askButton: 'Ask',
    listeningTranscript: 'Listening to your voice... Speak clearly into your microphone',
    categoryPricing: '💰 Fair Pricing',
    categorySchemes: '🏛️ PM Vishwakarma Yojana',
    categoryGItag: '🏷️ GI Certification',
    categoryPhotography: '📸 Craft Photography',
    categoryPackaging: '📦 Safe Packaging',
    categoryPayments: '💳 Digital UPI & Bank',
    categoryGeneral: '🌸 Artisan Guide',
    welcomeSpoken: 'Welcome to Bharat TULIP Artisan Voice Studio. I am your live voice companion. Tap the microphone to talk with me about craft pricing, government schemes, or photography.',
    welcomeDisplay: '**Welcome to Bharat TULIP Artisan Voice Studio** 🌸\n\nI am your live voice companion. I can guide you on:\n- **Fair Artisan Pricing:** Calculating raw materials, hourly wage, and profit margin\n- **PM Vishwakarma Yojana:** Claiming the ₹15,000 tool grant and 5% interest loans\n- **GI Certification:** Protecting regional handicraft authenticity\n- **Product Photography:** Capturing showroom-grade craft photos in natural light\n\nTap the microphone to speak, or type your question below!',
    clearChatNotice: 'Chat cleared. Tap the microphone or type a question below.',
  },
};

export interface ProductImagePromptConfig {
  askImageSpoken: string;
  askImageHeadline: string;
  askImageSubtext: string;
  takePhotoText: string;
  uploadPhotoText: string;
  dragDropText: string;
  sampleCraftsTitle: string;
  imageReceivedSpoken: string;
  imageEnhancingText: string;
  retakeText: string;
  continueText: string;
}

export const PRODUCT_IMAGE_PROMPTS: Record<SupportedLanguageCode, ProductImagePromptConfig> = {
  hi: {
    askImageSpoken: 'कारीगर जी, कृपया अपने हस्तशिल्प उत्पाद की एक साफ़ फोटो खींचिए या अपलोड कीजिए।',
    askImageHeadline: 'उत्पाद की फोटो खींचिए या अपलोड करें',
    askImageSubtext: 'कैमरे से फोटो लें या गैलरी से अपलोड करें। एआई बैकग्राउंड हटाकर इसे स्टूडियो लुक देगा।',
    takePhotoText: 'कैमरा खोलें',
    uploadPhotoText: 'फोटो अपलोड करें',
    dragDropText: 'फोटो यहाँ छोड़ें या क्लिक करके चुनें',
    sampleCraftsTitle: 'या नीचे दिए गए नमूना हस्तशिल्प में से चुनें:',
    imageReceivedSpoken: 'बहुत सुंदर! आपके उत्पाद की फोटो प्राप्त हो गई है। एआई स्टूडियो बैकग्राउंड तैयार कर रहा है।',
    imageEnhancingText: 'एआई स्टूडियो बैकग्राउंड तैयार कर रहा है...',
    retakeText: 'दूसरी फोटो लें',
    continueText: 'उत्पाद विवरण के लिए आगे बढ़ें',
  },
  ta: {
    askImageSpoken: 'வணக்கம்! தயவுசெய்து உங்கள் கைவினைப் பொருளின் ஒரு தெளிவான புகைப்படத்தைப் பதிவேற்றவும் அல்லது கேமராவில் எடுக்கவும்.',
    askImageHeadline: 'தயாரிப்பு புகைப்படத்தை எடுக்கவும் அல்லது பதிவேற்றவும்',
    askImageSubtext: 'கேமரா மூலம் படம் எடுக்கவும் அல்லது பதிவேற்றவும். AI பின்னணியை அகற்றி ஸ்டுடியோவாக மாற்றும்.',
    takePhotoText: 'கேமரா திறக்கவும்',
    uploadPhotoText: 'புகைப்படத்தைப் பதிவேற்றவும்',
    dragDropText: 'புகைப்படத்தை இங்கே இழுத்து விடவும் அல்லது கிளிக் செய்யவும்',
    sampleCraftsTitle: 'அல்லது மாதிரி கைவினைப் பொருளைத் தேர்ந்தெடுக்கவும்:',
    imageReceivedSpoken: 'அருமை! உங்கள் தயாரிப்பின் புகைப்படம் பெறப்பட்டது. AI ஸ்டுடியோ பின்னணியை உருவாக்குகிறது.',
    imageEnhancingText: 'AI ஸ்டுடியோ பின்னணியை உருவாக்குகிறது...',
    retakeText: 'வேறு படம் எடுக்கவும்',
    continueText: 'அடுத்த படிக்குச் செல்லவும்',
  },
  te: {
    askImageSpoken: 'నమస్కారం! దయచేసి మీ హస్తకళా వస్తువు యొక్క స్పష్టమైన ఫోటోను అప్‌లోడ్ చేయండి లేదా కెమెరాతో తీయండి.',
    askImageHeadline: 'వస్తువు ఫోటోను తీయండి లేదా అప్‌లోడ్ చేయండి',
    askImageSubtext: 'కెమెరా ద్వారా ఫోటో తీయండి లేదా అప్‌లోడ్ చేయండి. AI స్టూడియో బ్యాక్‌గ్రౌండ్‌ను మెరుగుపరుస్తుంది.',
    takePhotoText: 'కెమెరా తెరవండి',
    uploadPhotoText: 'ఫోటో అప్‌లోడ్ చేయండి',
    dragDropText: 'ఫోటోను ఇక్కడ డ్రాప్ చేయండి లేదా క్లిక్ చేయండి',
    sampleCraftsTitle: 'లేదా నమూనా చేతిపనులను ఎంచుకోండి:',
    imageReceivedSpoken: 'చాలా బాగుంది! మీ ఉత్పత్తి ఫోటో స్వీకరించబడింది. AI స్టూడియో బ్యాక్‌గ్రౌండ్ సిద్ధం చేస్తోంది.',
    imageEnhancingText: 'AI స్టూడియో బ్యాక్‌గ్రౌండ్ సిద్ధం చేస్తోంది...',
    retakeText: 'మరో ఫోటో తీయండి',
    continueText: 'తదుపరి దశకు కొనసాగండి',
  },
  bn: {
    askImageSpoken: 'নমস্কার! অনুগ্রহ করে আপনার তৈরি হস্তশিল্পের একটি পরিষ্কার ছবি তুলুন বা আপলোড করুন।',
    askImageHeadline: 'পণ্যের ছবি তুলুন বা আপলোড করুন',
    askImageSubtext: 'ক্যামেরায় ছবি তুলুন বা আপলোড করুন। এআই স্টুডিও ব্যাকগ্রাউন্ড তৈরি করবে।',
    takePhotoText: 'ক্যামেরা খুলুন',
    uploadPhotoText: 'ছবি আপলোড করুন',
    dragDropText: 'এখানে ছবি ড্রপ করুন বা ক্লিক করুন',
    sampleCraftsTitle: 'অথবা একটি নমুনা হস্তশিল্প নির্বাচন করুন:',
    imageReceivedSpoken: 'অসাধারণ! আপনার হস্তশিল্পের ছবি পেয়েছি। এআই স্টুডিও ব্যাকগ্রাউন্ড সাজাচ্ছে।',
    imageEnhancingText: 'এআই স্টুডিও ব্যাকগ্রাউন্ড সাজাচ্ছে...',
    retakeText: 'অন্য ছবি নিন',
    continueText: 'পরবর্তী ধাপে এগিয়ে যান',
  },
  mr: {
    askImageSpoken: 'नमस्कार! कृपया तुमच्या हस्तकलेच्या उत्पादनाचा एक स्पष्ट फोटो काढा किंवा अपलोड करा.',
    askImageHeadline: 'उत्पादनाचा फोटो काढा किंवा अपलोड करा',
    askImageSubtext: 'कॅमेराने फोटो घ्या किंवा अपलोड करा. एआय पार्श्वभूमी बदलून स्टुडिओ लूक देईल.',
    takePhotoText: 'कॅमेरा उघडा',
    uploadPhotoText: 'फोटो अपलोड करा',
    dragDropText: 'फोटो येथे टाका किंवा क्लिक करा',
    sampleCraftsTitle: 'किंवा नमुना हस्तकला निवडा:',
    imageReceivedSpoken: 'खूप छान! तुमच्या उत्पादनाचा फोटो मिळाला आहे. एआय स्टुडिओ लूक तयार करत आहे.',
    imageEnhancingText: 'एआय स्टुडिओ लूक तयार करत आहे...',
    retakeText: 'दुसरा फोटो घ्या',
    continueText: 'पुढील चरणावर जा',
  },
  gu: {
    askImageSpoken: 'નમસ્તે! કૃપા કરીને તમારા હસ્તકલા ઉત્પાદનનો એક સ્પષ્ટ ફોટો લો અથવા અપલોડ કરો.',
    askImageHeadline: 'ઉત્પાદનનો ફોટો લો અથવા અપલોડ કરો',
    askImageSubtext: 'કેમેરાથી ફોટો લો અથવા અપલોડ કરો. એઆઈ સ્ટુડિયો બેકગ્રાઉન્ડ તૈયાર કરશે.',
    takePhotoText: 'કેમેરો ખોલો',
    uploadPhotoText: 'ફોટો અપલોડ કરો',
    dragDropText: 'અહીં ફોટો મૂકો અથવા ક્લિક કરો',
    sampleCraftsTitle: 'અથવા નમૂના હસ્તકલા પસંદ કરો:',
    imageReceivedSpoken: 'ખૂબ સરસ! તમારા ઉત્પાદનનો ફોટો મળી ગયો છે. એઆઈ સ્ટુડિયો તૈયાર કરી રહ્યું છે.',
    imageEnhancingText: 'એઆઈ સ્ટુડિયો તૈયાર કરી રહ્યું છે...',
    retakeText: 'બીજો ફોટો લો',
    continueText: 'આગળ વધો',
  },
  kn: {
    askImageSpoken: 'ನಮಸ್ಕಾರ! ದಯವಿಟ್ಟು ನಿಮ್ಮ ಕರಕುಶಲ ಉತ್ಪನ್ನದ ಸ್ಪಷ್ಟ ಫೋಟೋವನ್ನು ತೆಗೆಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    askImageHeadline: 'ಉತ್ಪನ್ನದ ಫೋಟೋ ತೆಗೆಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    askImageSubtext: 'ಕ್ಯಾಮೆರಾದಿಂದ ಫೋಟೋ ತೆಗೆಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. AI ಸ್ಟುಡಿಯೋ ಹಿನ್ನೆಲೆಯನ್ನು ರಚಿಸುತ್ತದೆ.',
    takePhotoText: 'ಕ್ಯಾಮೆರಾ ತೆರೆಯಿರಿ',
    uploadPhotoText: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    dragDropText: 'ಫೋಟೋವನ್ನು ಇಲ್ಲಿ ಡ್ರಾಪ್ ಮಾಡಿ ಅಥವಾ ಕ್ಲಿಕ್ ಮಾಡಿ',
    sampleCraftsTitle: 'ಅಥವಾ ಮಾದರಿ ಕರಕುಶಲತೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ:',
    imageReceivedSpoken: 'ತುಂಬಾ ಚೆನ್ನಾಗಿದೆ! ನಿಮ್ಮ ಉತ್ಪನ್ನದ ಫೋಟೋ ಸ್ವೀಕರಿಸಲಾಗಿದೆ. AI ಸ್ಟುಡಿಯೋ ಸಿದ್ಧಪಡಿಸುತ್ತಿದೆ.',
    imageEnhancingText: 'AI ಸ್ಟುಡಿಯೋ ಸಿದ್ಧಪಡಿಸುತ್ತಿದೆ...',
    retakeText: 'ಮತ್ತೊಂದು ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ',
    continueText: 'ಮುಂದಿನ ಹಂತಕ್ಕೆ ಮುಂದುವರಿಯಿರಿ',
  },
  ml: {
    askImageSpoken: 'നമസ്കാരം! ദയവായി നിങ്ങളുടെ കരകൗശല ഉൽപ്പന്നത്തിന്റെ വ്യക്തമായ ഫോട്ടോ എടുക്കുക അല്ലെങ്കിൽ അപ്‌ലോഡ് ചെയ്യുക.',
    askImageHeadline: 'ഉൽപ്പന്നത്തിന്റെ ഫോട്ടോ എടുക്കുക അല്ലെങ്കിൽ അപ്‌ലോഡ് ചെയ്യുക',
    askImageSubtext: 'ക്യാമറയിൽ ഫോട്ടോ എടുക്കുക അല്ലെങ്കിൽ അപ്‌ലോഡ് ചെയ്യുക. AI സ്റ്റുഡിയോ പശ്ചാത്തലം ഒരുക്കും.',
    takePhotoText: 'ക്യാമറ തുറക്കുക',
    uploadPhotoText: 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
    dragDropText: 'ഫോട്ടോ ഇവിടെ ഡ്രോപ്പ് ചെയ്യുക അല്ലെങ്കിൽ ക്ലിക്ക് ചെയ്യുക',
    sampleCraftsTitle: 'അല്ലെങ്കിൽ ഒരു മാതൃകാ കരകൗശലം തിരഞ്ഞെടുക്കുക:',
    imageReceivedSpoken: 'വളരെ മനോഹരം! നിങ്ങളുടെ ഉൽപ്പന്നത്തിന്റെ ഫോട്ടോ ലഭിച്ചു. AI സ്റ്റുഡിയോ പശ്ചാത്തലം മാറ്റുന്നു.',
    imageEnhancingText: 'AI സ്റ്റുഡിയോ പശ്ചാത്തലം മാറ്റുന്നു...',
    retakeText: 'മറ്റൊരു ഫോട്ടോ എടുക്കുക',
    continueText: 'അടുത്ത ഘട്ടത്തിലേക്ക് പോകുക',
  },
  or: {
    askImageSpoken: 'ନମସ୍କାର! ଦୟାକରି ଆପଣଙ୍କ ହସ୍ତଶିଳ୍ପ ଉତ୍ପାଦର ଏକ ସଫା ଫଟୋ ଉଠାନ୍ତୁ କିମ୍ବା ଅପଲୋଡ୍ କରନ୍ତୁ।',
    askImageHeadline: 'ଉତ୍ପାଦର ଫଟୋ ଉଠାନ୍ତୁ କିମ୍ବା ଅପଲୋଡ୍ କରନ୍ତୁ',
    askImageSubtext: 'କ୍ୟାମେରାରେ ଫଟୋ ନିଅନ୍ତୁ କିମ୍ବା ଅପଲୋଡ୍ କରନ୍ତୁ। AI ଷ୍ଟୁଡିଓ ବ୍ୟାକଗ୍ରାଉଣ୍ଡ ତିଆରି କରିବ।',
    takePhotoText: 'କ୍ୟାମେରା ଖୋଲନ୍ତୁ',
    uploadPhotoText: 'ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ',
    dragDropText: 'ଏଠାରେ ଫଟୋ ଡ୍ରପ୍ କରନ୍ତୁ କିମ୍ବା କ୍ଲିକ୍ କରନ୍ତୁ',
    sampleCraftsTitle: 'କିମ୍ବା ଏକ ନମୁନା ହସ୍ତକଳା ଚୟନ କରନ୍ତୁ:',
    imageReceivedSpoken: 'ଅତି ସୁନ୍ଦର! ଆପଣଙ୍କ ଉତ୍ପାଦ ଫଟୋ ମିଳିଛି। AI ଷ୍ଟୁଡିଓ ବ୍ୟାକଗ୍ରାଉଣ୍ଡ ସଜାଉଛି।',
    imageEnhancingText: 'AI ଷ୍ଟୁଡିଓ ବ୍ୟାକଗ୍ରାଉଣ୍ଡ ସଜାଉଛି...',
    retakeText: 'ଅନ୍ୟ ଏକ ଫଟୋ ନିଅନ୍ତୁ',
    continueText: 'ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପକୁ ଯାଆନ୍ତୁ',
  },
  pa: {
    askImageSpoken: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਹੱਥ ਨਾਲ ਬਣੇ ਉਤਪਾਦ ਦੀ ਇੱਕ ਸਾਫ਼ ਫੋਟੋ ਲਓ ਜਾਂ ਅੱਪਲੋਡ ਕਰੋ।',
    askImageHeadline: 'ਉਤਪਾਦ ਦੀ ਫੋਟੋ ਲਓ ਜਾਂ ਅੱਪਲੋਡ ਕਰੋ',
    askImageSubtext: 'ਕੈਮਰੇ ਨਾਲ ਫੋਟੋ ਖਿੱਚੋ ਜਾਂ ਅੱਪਲੋਡ ਕਰੋ। AI ਸਟੂਡੀਓ ਬੈਕਗ੍ਰਾਊਂਡ ਤਿਆਰ ਕਰੇਗਾ।',
    takePhotoText: 'ਕੈਮਰਾ ਖੋਲ੍ਹੋ',
    uploadPhotoText: 'ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
    dragDropText: 'ਫੋਟੋ ਇੱਥੇ ਸੁੱਟੋ ਜਾਂ ਕਲਿੱਕ ਕਰੋ',
    sampleCraftsTitle: 'ਜਾਂ ਨਮੂਨਾ ਦਸਤਕਾਰੀ ਚੁਣੋ:',
    imageReceivedSpoken: 'ਬਹੁਤ ਵਧੀਆ! ਤੁਹਾਡੇ ਉਤਪਾਦ ਦੀ ਫੋਟੋ ਮਿਲ ਗਈ ਹੈ। AI ਸਟੂਡੀਓ ਬੈਕਗ੍ਰਾਊਂਡ ਤਿਆਰ ਕਰ ਰਿਹਾ ਹੈ।',
    imageEnhancingText: 'AI ਸਟੂਡੀਓ ਬੈਕਗ੍ਰਾਊਂਡ ਤਿਆਰ ਕਰ ਰਿਹਾ ਹੈ...',
    retakeText: 'ਦੂਜੀ ਫੋਟੋ ਲਓ',
    continueText: 'ਅਗਲੇ ਕਦਮ ਤੇ ਜਾਓ',
  },
  en: {
    askImageSpoken: 'Please upload or take a clear photo of your handcrafted product.',
    askImageHeadline: 'Capture or Upload Your Product Photo',
    askImageSubtext: 'Take a photo with your camera or upload from your device. AI will automatically enhance and create a studio photoshoot backdrop.',
    takePhotoText: 'Open Camera',
    uploadPhotoText: 'Upload Photo',
    dragDropText: 'Drag & drop your product photo here, or click to browse',
    sampleCraftsTitle: 'Or choose a sample handcrafted craft:',
    imageReceivedSpoken: 'Wonderful! Your product image has been received. AI is enhancing the studio lighting and backdrop.',
    imageEnhancingText: 'AI studio enhancement in progress...',
    retakeText: 'Change Photo',
    continueText: 'Continue to Voice Description',
  },
};
